---
title: "Aquaculture"
output:
  pdf_document: default
  html_document: default
  word_document: default
bibliography: Aquaculture.bib
header-includes: 
- \usepackage{float}
- \usepackage[bottom]{footmisc}
---
<!-- STOP!!!!! INSERT THE FILE NAME OF YOUR .bib BIBLIOGRAPHY ABOVE.--> 

```{r setup,  echo = F, message=F}

#Load packages
library(knitr)
library(rmarkdown)

```

The purpose of this form is to provide the methods used to collect, process, and analyze derived data prior to data submission for all EDAB reports. This information will be compiled into the State of the Ecosystem Tech Memo, AND be used to meet metadata requirements put forth by the Public Access to Research Results (PARR) directive. 

For the tech memo, we will be documenting the methods behind each indicator to the level of a peer-reviewed document.


## Contributor name(s)
Sean Hardison

## Data name
Aquaculture indicators

### Indicator category 
Indicate from the list below which category the contributed data fall under by deleting other entries.

<!--
1. Database pull
2. Database pull with analysis-->
3. Synthesis of published information
<!--4. Extensive analysis; not yet published
5. Published methods-->


## Methods
Aquaculture data included in the SOE report were time series of number of oysters sold in Virginia, Maryland, and New Jersey. 


### Data source(s) (All types)
Virginia oyster harvest data are collected from mail and internet-based surveys of active oyster aquaculture operations on both sides of the Chesapeake Bay, which are then synthesized in an annual report [@Hudson2017a]. In Maryland, shellfish aquaculturists are required to report their monthly harvests to the Maryland Department of Natural Resources (MD-DNR). The MD-DNR then aggregates the harvest data for release in the Maryland Aquaculture Coordinating Council Annual Report [@ACC2017], from which data were collected. Similar to Virginia, New Jersey releases annual reports synthesizing electronic survey results from lease-holding shellfish growers. Data from New Jersey reflects cage reared oysters grown from hatchery seed [@Calvo2017]. 


### Data extraction 
Data were collected directly from state aquaculture reports. Oysters harvest data in MD was reported in bushels which were then converted to individual oysters by an estimate of 300 oysters bushel$^{-1}$.

### Data analysis
No data analyses occurred for this indicator.

#### Public availability statement
Source data are publicly available in referenced reports.

#### Point of contact - Whom should be contacted?
Sean Hardison

#### Data steward (can be POC; in charge of keeping data updated)
Sean Hardison

#### References
<!-- References must be submitted in BibTeX format. When compiling this document, they will appear in this section. There is no need to write them out here. Don't forget to include the name of your .bib file in the YAML header (fill in XYZ.bib in YAML header)!!!!!--> 






