---
title: "Publishing bookdown to gh-pages with Travis CI"
author: "Sarah"
date: "8/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bookdown publishing instructions for next time

This is copied from the [bookdown book](https://bookdown.org/yihui/bookdown/github.html) but streamlined to make it more of a recipe so I don't forget the steps next time. 

Copied in the order I did things to implement gh-pages:

>## GitHub
>
>You can host your book on GitHub\index{GitHub} for free via GitHub Pages (https://pages.github.com). GitHub supports Jekyll (http://jekyllrb.com), a static website builder, to build a website from Markdown files. That may be the more common use case of GitHub Pages, but GitHub also supports arbitrary static HTML files, so you can just host the HTML output files of your book on GitHub. The key is to create a hidden file `.nojekyll` that tells GitHub that your website is not to be built via Jekyll, since the **bookdown** HTML output is already a standalone website. 

[...]

>An alternative approach is to create a `gh-pages` branch in your repository, build the book, put the HTML output (including all external resources like images, CSS, and JavaScript files) in this branch, and push the branch to the remote repository. If your book repository does not have the `gh-pages` branch, you may use the following commands to create one:

**Sarah's notes**: Do this on your _local_ machine, using the terminal under the git-tracked directory, pushing to the github repo last. Don't be tempted to make the gh-pages branch on github first, it causes pain. Using [checkout --orphan](https://git-scm.com/docs/git-checkout) means you are making a new branch that has no history (you don't need to carry the version control history here; it stays on the master branch). Next you are removing all the files from this new branch using [rm -rf .](https://git-scm.com/docs/git-rm) because it will only have the compiled book files on it. All rmd files, etc will remain on the master branch. At the end of this step in the terminal you push to create the gh-pages branch on github. You should see it there, containing only .nojekyll

>
>From bookdown github chapter:
>    
```bash
# assume you have initialized the git repository,
# and are under the directory of the book repository now

# create a branch named gh-pages and clean up everything
git checkout --orphan gh-pages
git rm -rf .

# create a hidden file .nojekyll
touch .nojekyll
git add .nojekyll

git commit -m"Initial commit"
git push origin gh-pages
```
>    
>
>If you are on Windows, you may not have the `touch` command, and you can create the file in R using `file.create('.nojekyll')`.

[...]

>One service that you can utilize is Travis CI (https://travis-ci.org).\index{Travis CI} It is free for public repositories on GitHub, and was designed for continuous integration (CI) of software packages. Travis CI can be connected to GitHub in the sense that whenever you push to GitHub, Travis can be triggered to run certain commands/scripts on the latest version of your repository.^[You need to authorize the Travis CI service for your repository on GitHub first. See https://docs.travis-ci.com/user/getting-started/ for how to get started with Travis CI.] These commands are specified in a YAML file named `.travis.yml` in the root directory of your repository, and they are usually for the purpose of testing software, but in fact they are quite open-ended, meaning that you can run arbitrary commands on a Travis (virtual) machine. That means you can certainly run your own scripts to build your book on Travis. Note that Travis only supports Ubuntu and Mac OS X at the moment, so you should have some basic knowledge about Linux/Unix commands.

>The next question is, how to publish the book built on Travis to GitHub? Basically you have to grant Travis write access to your GitHub repository. This authorization can be done in several ways, and the easiest one to beginners may be a personal access token. Here are a few steps you may follow:

>1. Create a [personal access token](http://bit.ly/2cEBYWB) for your account on GitHub (make sure to enable the "repo" scope so that using this token will enable writing to your GitHub repos).
>1. Encrypt it in the environment variable `GITHUB_PAT` via command line `travis encrypt` and store it in `.travis.yml`, 
e.g `travis encrypt GITHUB_PAT=TOKEN`. If you do not know how to install or use the Travis command-line tool, simply save this environment variable via https://travis-ci.org/user/repo/settings where `user` is your GitHub ID, and `repo` is the name of the repository.
>1. You can clone this `gh-pages` branch on Travis using your GitHub token, add the HTML output files from R Markdown (do not forget to add figures and CSS style files as well), and push to the remote repository.

[...]

**Sarah's notes**: I did everything over the web and did not encrypt the personal access token. There is good documentation of how to generate the personal access token [here](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/). I pasted the token into the travis CI repository settings (you probably need to be logged in at https://travis-ci.org/NOAA-EDAB/tech-memo/settings) under environment variables as demonstrated [here](https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings), with the name GITHUB_PAT. If we want encryption in the future there are options [here](https://docs.travis-ci.com/user/encryption-keys). The last step above is actually deployment, which is taken care of by a script. I think it is easier to just show the scripts used now below. Note that pushing a file called .travis.yml to the github repository will trigger travis to start building, so it may be best to have everything else in place first.

Once the files are in place, the fiddling was largely to set up the virtual machine in travis correctly; expect to build your R environment, including all packages, and importantly system dependencies for the packages (I'm looking at you `rgdal` and `ncdf4`) to make the build work. Note also that packages from github repositories (not on CRAN) are listed both under Imports and Remotes in the DESCRIPTION file. After the first successful build, travis can cache the r packages so later builds should be faster.

Needed files, with the ones that worked for the NOAA-EDAB/tech-memo repository (based on those in the bookdown-demo repository: https://github.com/rstudio/bookdown-demo/. ):

1. DESCRIPTION (dummy aside from R package dependencies)

```dcf
Package: placeholder
Title: does not matter
Description: This is a description. 
Version: 0.0.1
Imports: 
  bookdown, 
  rmarkdown,
  tidyverse,
  data.table,
  nlme,
  AICcmodavg,
  rgdal,
  maps,
  mapdata,
  png,
  marmap,
  rerddap,
  vegan,
  mgcv,
  rpart,
  Kendall,
  zoo,
  colorRamps,
  Hmisc,
  raster,
  grid,
  gridExtra,
  stringr,
  ncdf4,
  magick,
  readxl,
  reshape2,
  RColorBrewer,
  cowplot,
  stats,
  geosphere,
  readr,
  sp,
  openxlsx,
  lubridate, 
  rgeos,
  Survdat
Remotes: 
  rstudio/bookdown,
  slucey/Rsurvey/Survdat
```

2. _build.sh (the command(s) to make the book)

```bash
#!/bin/sh

Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
```

3. _deploy.sh (tells travis and github to work nicely together and build the book)

```bash
#!/bin/sh

set -e

[ -z "${GITHUB_PAT}" ] && exit 0
[ "${TRAVIS_BRANCH}" != "master" ] && exit 0

git config --global user.email "Sarah.Gaichas@noaa.gov"
git config --global user.name "Sarah Gaichas"

git clone -b gh-pages https://${GITHUB_PAT}@github.com/${TRAVIS_REPO_SLUG}.git book-output
cd book-output
cp -r ../_book/* ./
git add --all *
git commit -m"Update the book" || true
git push -q origin gh-pages
```

4. .travis.yml (defines programming language, system dependencies, and runs scripts)

```yaml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
pandoc_version: 2.1.1
cache: packages

before_install:
- sudo apt-get install libgdal1-dev libproj-dev gdal-bin proj-bin
- sudo apt-get install libgeos-dev
- sudo apt-get install libnetcdf-dev netcdf-bin
- sudo apt-get install libmagick++-dev

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
```

Hope this helps the next time, assuming everything hasn't changed.

Nice examples of books: https://github.com/daviddalpiaz/appliedstats  
Websites consulted: https://bookdown.org/yihui/bookdown/github.html  
https://juliasilge.com/blog/beginners-guide-to-travis/  
https://nathaneastwood.github.io/2017/05/16/automatically-building-testing-and-deploying-bookdown-with-travis-and-github-pages/  
https://www.wjakethompson.com/post/blogdown-gh-pages-travis-ci/  
http://seankross.com/2016/11/17/How-to-Start-a-Bookdown-Book.html  
http://happygitwithr.com/  



