---
title: "Technical Documentation, State of the Ecosystem Report"
author: "Northeast Fisheries Science Center"
date: "`r format(Sys.Date(), '%e %B %Y')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: ["conceptmods.bib", "trend_analysis.bib", "EPU.bib", "survey_data.bib", "Bennet_indicator.bib", "Revenue_Diversity.bib", "Aquaculture.bib", "NE_HAB.bib", "MAB_HAB.bib", "Comm_rel_vuln.bib", "Comm_climate_vuln.bib", "RW.bib", "thermal_hab_proj.bib"," long_term_sst.bib", "seasonal_sst_anomaly_maps.bib", "ich_div.bib", "Species_dist.bib", "CHL_PPD.bib", "Condition.bib", "productivity_tech_memo.bib"]
biblio-style: apalike
link-citations: yes
github-repo: NOAA-EDAB/tech-memo
description: "This book documents each indicator and analysis used in State of the Ecosystem reporting"
---
# Introduction {-}

The purpose of this document is to collate the methods used to access, collect, process, and analyze derived data ("indicators") used to describe the status and trend of social, economical, ecological, and biological conditions in the Northeast Shelf Large Marine Ecosystem (ADD MAP OF REGION). These indicators are further synthesized in State of the Ecosystem Reports produced annually by the [Northeast Fisheries Science Center](https://www.nefsc.noaa.gov/) for the [New England Fisheries Management Council](https://www.nefmc.org/) and the [Mid-Atlantic Fisheries Management Council](http://www.mafmc.org/). The methods to construct each indicator are described in the subsequent chapters, with each chapter title corresponding to an indicator or analysis present in the State of the Ecosystem Report. Each chapter is derived from a common template to ensure consistency between indicators and the level of documentation is intended to be on par with a peer-reviewed document. Further, the document contains metadata for each indicator according to the [Public Access to Research Results (PARR) directive](http://obamawhitehouse.archives.gov/sites/default/files/microsites/ostp/ostp_public_access_memo_2013.pdf).

--------------
