# Bottom temperature - High Resolution

**Description**: Seasonal bottom temperatures on the Northeast Continental Shelf between 1959 and 2022 in a 1/12° grid. 

**Indicator category**: Published Methods, Synthesis of published information

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2023); State of the Ecosystem - Mid-Atlantic Bight (2023)

**Contributor(s)**: Hubert du Pontavice, Vincent Saba, Zhuomin Chen

**Data steward**: Hubert du Pontavice, hubert.dupontavice@noaa.gov

**Point of contact**: Hubert du Pontavice, hubert.dupontavice@noaa.gov

**Public availability statement**: Source data are NOT publicly available. Please email hubert.dupontavice@noaa.gov for further information and queries of bottom temperature source data.

## Methods

### Data sources

#### Study area
The bottom temperature product covered the northeast U.S. shelf marine ecosystem (NEUS) and specifically an area of four Ecological Production Units (EPUs) defined by NOAA's Northeast Fisheries Science Center (https://noaa-edab.github.io/tech-doc/epu.html).

#### Design of the gridded bottom temperature time series

The bottom temperature product is in a horizontal 1/12 degree grid between 1959 and 2022 and is made of daily bottom temperature estimates from:
- Bias-corrected ROMS-NWA (ROMScor) between 1959 and 1992 which was regridded in the same 1/12 degree grid as GLORYS and PSY4V3R1 using bilinear interpolation;
- GLORYS12v1 in its original 1/12 degree grid between 1993 and 2019;
- PSY4V3R1 in its original 1/12 degree grid between 2020 and 2022.

### Data extraction


### Data analysis

#### Ocean model data

Three ocean models were used to get high-resolution daily bottom temperature on the NEUS between 1959 and 2021. For the period between 1959 and 1992, we used daily ocean bottom temperature from the long-term (1958–2007) high-resolution numerical simulation of the Northwest Atlantic Ocean in the Regional Ocean Modelling System (ROMS), a split-explicit, free-surface, terrain-following, hydrostatic, primitive equation model (@Shchepetkin2005). The model domain covers the Northwest Atlantic Ocean with ~7km horizontal resolution and 40 vertical terrain-following layers. A detailed description of ROMS-NWA can be found in @Chen2018.

For the period between 1992 and 2019, the daily bottom temperature outputs from the GLORYS12v1 ocean reanalysis product were used. GLORYS12v1 is a global ocean, eddy-resolving, and data assimilated hindcast from Mercator Ocean (@Lellouche2018; @Lellouche2021) with 1/12 degree horizontal resolution and 50 vertical levels. The base ocean model is the Nucleus for European Modelling of the Ocean 3.1 (NEMO 3.1; Madec, 2016) driven at the surface by the European Centre for the Medium-Range Weather Forecasts (ECMWF) ERA-Interim reanalysis (@Dee2011). Remotely sensed and in situ observations are jointly assimilated by means of a reduced-order Kalman filter.

For the period between 2020 and 2022, we used daily bottom temperature from the Operational Mercator global ocean analysis and forecast system (PSY4V3R1 as in @Lellouche et al2018). The PSY4V3R1 is a global ocean, eddy-resolving, monitoring forecasting system (@Lellouche2018; Mercator Ocean International, 2016) with the same ocean model grid
(1/12 degree horizontal resolution and 50 vertical levels) and has many similarities with GLORYS12v1. Remotely sensed and in situ observations are also jointly assimilated by means of a reduced-order Kalman filter.

#### Bias-correction process of NWA-ROMS

We used the methodology implemented in du Pontavice et al. (2022) based on observed climatology. The first step was to regrid ROMS-NWA bottom temperature over the same 1/10 degree horizontal grid as the NWARC using bilinear interpolation. Then, we conducted the bottom temperature bias-correction in the 1/10 degree NWARC grid using monthly climatologies from NWARC over four decadal periods from 1955 to 1994. A monthly bias was calculated in each 1/10 degree grid cell and for each decade (1955–1964, 1965–1974, 1975–1984, 1985–1994). Based on this monthly bias, we estimated a daily bias for each decade in each grid cell. Lastly, for each ROMS-NWA
grid cell we identified the bias from the closest 1/10 degree NWARC grid cell and subtracted the daily bias to the daily ROMS-NWA bottom temperature for all years and days of each decade.



### Data processing

Derived bottom temperature data were formatted for inclusion in the `ecodata` R package using the R code found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_bottom_temp_comp.R). 

### Plotting

Code for plotting Georges Bank and Gulf of Maine bottom temperature time series can be found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/chunk-scripts/LTL.Rmd-NE-seasonal-bt-anom.R). 

```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/LTL_NE.Rmd-seasonal-bt-anom.R"), eval=TRUE, echo = FALSE, fig.cap = "Seasonal bottom temperature time series in the New England."}

```
