# Calanus Stage

**Description**: Calanus abundance by life stage

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2021), State of the Ecosystem - Mid-Atlantic (2021)

**Indicator category**:  Database pull with analysis

**Contributor(s)**:  Ryan Morse

**Data steward**: Ryan Morse <ryan.morse@noaa.gov>
  
**Point of contact**: Ryan Morse <ryan.morse@noaa.gov>
  
**Public availability statement**:  Please contact Harvey Walsh (<harvey.walsh@noaa.gov>) for raw data. 


  
## Methods

### Data sources
Zooplankton data are from the National Oceanographic and Atmospheric Administration Marine Resources Monitoring, Assessment and Prediction (MARMAP) program and Ecosystem Monitoring (EcoMon) cruises detailed extensively in @Kane2007, @Kane2011, and @Morse2017.


### Data analysis
This index tracks the overall abundance of mature adult *Calanus finmarchicus* copepods and immature copepodite stage-5 (c5) *Calanus finmarchicus* copepods on the US Northeast Shelf ecosystem. The life cycle of *C. finmarchicus* relies on an overwintering phase (diapuse) where immature c5 copepodites build a lipid reserve prior to entering diapuse and remain at depth until favorable conditions for growth emerge. Because of this lipid reserve, diapausing c5 copepodites are a primary food source for many organisms, including the North Atlantic right whale.

Data are processed similarly to @Morse2017, except that cruises were partitioned into three seasons based on the median day of the year (DOY) for a given cruise. Cruises with median DOY between 0 and 120 were classified as spring cruises (i.e. their bimontly median dates correspond to 1 or 3). Cruises with a median DOY between 121 and 243 were classified as summer (bimonthly means of 5 or 7). Cruises with a median DOY between 244 and 366 were classified as fall (bimonthly mean cruise date of 9 or 11). Samples were assigned to EPUs based on their location, and transformed from raw counts to units of number per 100 m^-3 following MARMAP protocols. Samples were then aggregated to EPU by year using log transformed abundance. Cruises with less than 10 sampling days per cruise were removed due to incomplete surveys. Samples were limited to Calanus finmarchicus adults and copepodite stage-5 (c5) for inclusion as an indicator.


Code used to analyze calanus stage data can be found [at this link](https://github.com/NOAA-EDAB/tech-doc/blob/master/R/stored_scripts/CalanusStage_SOE.R). 

### Data processing

The Calanus Stage indicator was formatted for inclusion in the `ecodata` R package using the R script  found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_calanus_stage.R).

**catalog link**
<No associated catalog page>