# Chesapeake Bay Temperature Anomaly {#ch_bay_temp}

**Description**: Chesapeake Bay Satellite Sea Surface Temperature

**Found in**: State of the Ecosystem - Mid-Atlantic (2021)

**Indicator category**: Database pull with analysis

**Contributor(s)**: Bruce Vogt, Ron Vogel
  
**Data steward**: Ron Vogel, <ronald.vogel@noaa.gov>
  
**Point of contact**: Bruce Vogt, <bruce.vogt@noaa.gov> 
  
**Public availability statement**: Source data are publicly available.
  
**Public availability statement**: NOAA satellite data are publicly available.

## Methods
Seasonal average sea surface temperature (SST) from the Advanced Very High Resolution Radiometer (AVHRR) instrument, 2008-present, is composited from individual daytime and nighttime overpasses over the U.S. east coast into daily mean grids (~1.25 km), then the daily grids are averaged into gridded monthly temperature composites. Then the monthly temperatures are averaged into gridded seasonal temperature composites.

### Data sources
Data for the Chesapeake Bay seasonal sea surface temperature (SST) anomalies are derived from the AVHRR and VIIRS Multi-Sensor Composite Sea Surface Temperature data set, available from the NOAA CoastWatch East Coast Regional Node (https://eastcoast.coastwatch.noaa.gov/). The data set is a composite of overpasses from two instruments: the Advanced Very High Resolution Radiometer (AVHRR) instrument on the European MetOp satellites, and the Visible Infrared Imaging Radiometer Suite (VIIRS) on the S-NPP and NOAA satellites (starting with NOAA-20 and follow-on NOAA satellites). Data from all current operational satellites are used in order to increase geographic coverage on a per-day basis. SST is derived using the Advanced Clear-Sky Processor for Oceans (ACSPO) processing system for consistency across instruments (Petrenko et al., 2014; Petrenko et al., 2016). Only nighttime overpasses are incorporated into the composite, i.e. the data do not represent daytime solar heating of the water surface. The data extend from December 2006 to the present. The AVHRR 1 km spatial resolution data, and the VIIRS 750 m spatial resolution data, are co-gridded to an 830 m spatial grid.

More information about the AVHRR and VIIRS Multi-Sensor Composite SST data set is available at:
https://eastcoast.coastwatch.noaa.gov/cw_avhrr-viirs_sst.php

### Data analysis
Anomaly maps of SST are generated by creating long-term 'climatological' SST of the years 2008-2019 for each season. The seasonal SST for 2020 is then subtracted from the long-term seasonal average for each season.

Individual nighttime overpasses from all instruments on the current operational satellites are composited into daily gridded scenes. The daily gridded scenes are then averaged seasonally. A long-term ‘climatological’ seasonal average SST is generated for each season for the years from 2007 to the year immediately prior to the current year (max(Year) - 1). This reference period serves as a benchmark for comparing current observations. The current-year seasonal SST is then subtracted from the long-term seasonal average for all grid cells to create the anomaly map. Seasons for Chesapeake Bay are Dec-Feb (winter), Mar-May (spring), Jun-Aug (summer), and Sep-Nov (fall).

NOAA's CoastWatch Utilities Library contains the following library functions to generate the long-term average, seasonal average, anomaly (by subtraction), and map image:
  * cwcomposite, cwmath, cwrender
These are contained in the following Bash shell scripts:
  * nrt_daily_avhrr_sst.sh
  * nrt_monthly.sh
  * series_seasonal.sh
  * climatology_seasonal.sh
  * anomaly_gen.sh
The CoastWatch Utilities Library is free software which may be obtained from NOAA's CoastWatch Program:
https://coastwatch.noaa.gov/cw/user-resources/coastwatch-utilities.html

Python code used for database pull and analysis can be [found here.](https://github.com/NOAA-EDAB/tech-doc/blob/master/R/stored_scripts/cbibs)

### Data processing
Code for processing Chesapeake Bay temperature data can be found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_ch_bay_temp.R).

**catalog link**
<https://noaa-edab.github.io/catalog/ch_bay_temp.html>