# Chesapeake Bay Seasonal SST Anomalies 

**Description**:  Chesapeake Bay Seasonal SST Anomalies

**Found in**: State of the Ecosystem - Mid-Atlantic (2021+)

**Indicator category**: Database pull with analysis

**Contributor(s)**: Bruce Vogt, Ron Vogel
  
**Data steward**: Ron Vogel, <ronald.vogel@noaa.gov>
  
**Point of contact**: Bruce Vogt, <bruce.vogt@noaa.gov> 
  
**Public availability statement**: Source data are publicly available.
  
**Public availability statement**: Source data are publicly available [here](https://eastcoast.coastwatch.noaa.gov/cw_avhrr.php).

## Methods


### Data sources
Data for Chesapeake Bay seasonal sea surface temperature (SST) anomalies were derived from the NOAA Multi-satellite AVHRR SST data set, available from NOAA CoastWatch [East Coast Regional Node](https://eastcoast.coastwatch.noaa.gov). The data set is a composite of overpasses from all operational satellites currently flying the Advanced Very High Resolution Radiometer (AVHRR) instrument. SST is derived using the Operational Non-linear Multichannel SST Algorithm (Li, et al, 2001). Both daytime and nighttime overpasses are composited into daily and then seasonal SST products. The data extend from 2008 to present, and provide a 1.25 km x 1.25 km grid of SST measurements.

### Data analysis
Anomaly maps of SST are generated by creating long-term ‘climatological’ seasonal average SST for the years from 2008 to the year immediately prior to the current year. The reference period serves as a benchmark for comparing current observations. The current-year seasonal SST is then subtracted from the long-term seasonal average. Seasons for Chesapeake Bay are Dec-Feb (winter), Mar-May (spring), Jun-Aug (summer), and Sep-Nov (fall).



### Data processing
Code for processing Chesapeake Bay temperature data can be found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_ch_bay_temp.R). 




### Plotting
Code used to create the figure below can be [here](https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/LTL_MAB.Rmd-ches-bay-sst.R)
```{r , code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/LTL_MAB.Rmd-ches-bay-sst.R"), echo = F, eval = T, fig.cap="Maps of seasonal SST anomalies are generated for an SST range of +5.0 - -5.0 C. Positive values show current-season temperatures above the long-term seasonal average, whereas negative values show current-season temperatures below the long-term seasonal average.."}

```

### Resources
Li, X., W. Pichel, P. Clemente-Colón, V. Krasnopolsky, and J. Sapper. 2001. “Validation of Coastal Sea and Lake Surface Temperature Measurements Derived from NOAA/AVHRR Data.” International Journal of Remote Sensing 22 (7): 1285–1303. https://doi.org/10.1080/01431160151144350.

Li, X., W. Pichel, E. Maturi, P. Clemente-Colón, and J. Sapper. 2001. “Deriving the Operational Nonlinear Multichannel Sea Surface Temperature Algorithm Coefficients for NOAA-15 AVHRR/3.” International Journal of Remote Sensing 22 (4): 699–704. https://doi.org/10.1080/01431160010013793.

