# Cold Pool Index {#cold_pool}

**Description**: Cold Pool Index - three annual cold pool indices (and the standard errors) between 1958 and 2021. 

**Found in**: State of the Ecosystem - Mid-Atlantic (2020 (Different Methods), 2021 (Different Methods), 2022+)

**Indicator category**:Published methods, Extensive analysis, not yet published

**Contributor(s)**: Joseph Caracappa, Vincent Saba, Zhuomin Chen
  
**Data steward**: Joseph Caracappa <joseph.caracappa@noaa.gov>
  
**Point of contact**: Joseph Caracappa <joseph.caracappa@noaa.gov>
  
**Public availability statement**: Source data are NOT publicly available. Please email hubert.dupontavice@noaa.gov for further information and accessing the ROMS-NWA bottom temperature data.

## Methods
The methodology for the cold pool index changed between 2020, 2021, and 2022 SOEs. The most recent methods and at the top with older methods below those.


The cold pool is an area of relatively cold bottom water that forms on the US northeast shelf in the Mid-Atlantic Bight.


### Data sources
The three cold pool indices were calculated using a high-resolution long-term bottom temperature product. All the details on the bottom temperature dataset are available in the [Bottom Temperature - High Resolution](https://noaa-edab.github.io/tech-doc/bottom-temperature---high-resolution.html) chapter and in @noauthor_high-resolution_2023.


### Data analysis 

#### Cold Pool Domain

The first step was to define the Cold Pool domain, which is typically located within the MAB and the southern flank of Georges Bank (@chen_seasonal_2018; @houghton_middle_1982; @lentz_seasonal_2017). Here, we delineated a spatial domain covering the management area of the SNEMA yellowtail flounder (since this method was initially developed to study the Cold Pool impact on yellowtail flounder recruitment) comprising the MAB and in the SNE shelf between the 20 and 200 m isobaths (@chen_seasonal_2018; @chen_interannual_2020). We restricted the time period from June (to match the start of the settlement period; @sullivan_evidence_2005) to September (which is the average end date of the Cold Pool (calendar day 269) estimated by @chen_interannual_2020. The Cold Pool domain was defined as the area, wherein average bottom temperature was cooler than 10°C between June and September from 1959 to 2022. We then developed the three Cold Pool indices using bottom temperature from ocean models.

#### Cold Pool Index (Model_CPI)

The Cold Pool Index (Model_CPI) was adapted from @miller_state-space_2016 based on the method developed in @dupontavice_ocean_2022. Residual temperature was calculated in each grid cell, i, in the Cold Pool domain as the difference between the average bottom temperature at the year y (Ty) and the average bottom temperature over the period 1959–2022 $$({\bar{T}}_{i,\ 1958-2022})$$ between June and September. Model_CPI was calculated as the mean residual temperature over the Cold Pool domain such that:



$${{CPI}_y}=\ \frac{\sum_{i=1}^{n}{{(T}_{i,\ y}\ -\ {\bar{T}}_{i,\ 1958-2022})\ }}{n}$$





where n is the number of grid cells over the Cold Pool domain.

#### Persistence Index (Model_PI)

The temporal component of the Cold Pool was calculated using the persistence index (Model_PI). Model_PI measures the duration of the Cold Pool and is estimated using the month when bottom temperature rises above 10C after the Cold Pool is formed each year. We first selected the area over the cold pool domain in which bottom temperature falls below 10C between June and October. We then calculated the “residual month” in each grid cell, i, in the Cold Pool domain as the difference between the month when bottom temperature rises above 10C in year y and the average of those months over the period 1959–2022. Then, Model_PI was calculated as the mean “residual month” over the Cold Pool domain:


$${PI}_y=\ \frac{\sum_{i=1}^{n}{{(Month}_{i,\ y}\ -\ {\bar{Month}}_{i,\ 1958-2022})\ }}{n}$$


#### Spatial Extent Index (Model_SEI)

The spatial component of the Cold Pool and the habitat provided by the cold pool was calculated using the Spatial Extent Index (Model_SEI). The Model_SEI is estimated by the number of cells where bottom temperature remains below 10C for at least 2 months between June and September. 

The Bottom temperature data is the average ROMS-NWA bottom temperature over the decade $$d$$ in the grid cell $$i$$. All above methods @dupontavice_ocean_2022.

Bottom temperature from Glorys reanalysis and Global Ocean Physics Analysis were not being processed. 

Bottom temperature from ROMS-NWA (used for the period 1959-1992) were bias-corrected. Previous studies that focused on the ROMS-NWA-based Cold Pool highlighted strong and consistent warm bias in bottom temperature of about 1.5C during the stratified seasons over the period of 1958-2007 (@chen_seasonal_2018; @chen_interannual_2020). In order to bias-correct bottom temperature from ROMS-NWA, we used the monthly climatologies of observed bottom temperature from the Northwest Atlantic Ocean regional climatology (NWARC) over decadal periods from 1955 to 1994. The NWARC provides high resolution (1/10° grids) of quality-controlled in situ ocean temperature based on a large volume of observed temperature data (@seidov_northwest_2016, @seidov_northwest_2016-1) (https://www.ncei.noaa.gov/products/northwest-atlantic-regional-climatology). The first step was to re-grid the ROMS-NWA to obtain bottom temperature over the same 1/10° grid as the NWARC. Then, a monthly bias was calculated in each grid cell and for each decade (1955–1964, 1965–1974, 1975–1984, 1985–1994) in the MAB and in the SNE shelf:

$${BIAS}_{i,\ d}=\ T_{i,d}^{Climatology}\ -\ {\bar{T}}_{i,\ d}^{ROMS-NWA}$$


where $$T_{i,d}^{Climatology}$$ is the NWARC bottom temperature in the grid cell i for the decade d and $${\bar{T}}_{i,\ d}^{ROMS-NWA}$$ is the average ROMS-NWA bottom temperature over the decade d in the grid cell i. All above methods @dupontavice_ocean_2022.

### Data processing

Code used to process the cold pool inidcator can be found in the `ecodata` package [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_cold_pool.R). 

## 2021 Methods
**Point of Contact:**: Zhoumin Chen <zhuomin.chen@uconn.edu>

### Data sources
The three-dimensional temperature of the Northeast US shelf is downloaded from the CMEMS (https://marine.copernicus.eu/). Source data is available [at this link](https://resources.marine.copernicus.eu/?option=com_csw&task=results?option=com_csw&view=details&product_id=GLOBAL_REANALYSIS_PHY_001_030).

### Data analysis
Depth-averaged spatial temperature is calculated based on the daily Cold Pool dataset, which is quantified following @chen_seasonal_2018.

### Data processing

Code used to process the cold pool inidcator can be found in the `ecodata` package [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_cold_pool.R).

## 2020 Methods
**Point of Contact:**: Chris Melrose <chris.melrose@noaa.gov>

### Data sources
NEFSC Hydrographic Database
This data represents the annual mean bottom temperature residual for Sept-Oct in the Mid-Atlantic Bight cold pool region from 1977-2018.

### Data extraction 


### Data analysis
Methods published @miller_state-space_2016, [original MATLAB source code](https://github.com/NOAA-EDAB/tech-doc/tree/master/R/stored_scripts/cold_pool_analysis.txt) used in that paper was provided by Jon Hare and used in this analysis.

**catalog link**
<https://noaa-edab.github.io/catalog/cold_pool.html>





