# Forage Fish Energy Density {#energy_density}

**Description**: Forage Engery Density indicators

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2020+), State of the Ecosystem - Mid-Atlantic (2020+)

**Indicator category**: Database pull with analysis

**Contributor(s)**: Mark Wuenschel, Ken Oliveira and Kelcie Bean
  
**Data steward**: Mark Wuenschel <mark.wuenschel@noaa.gov>
  
**Point of contact**: Mark Wuenschel <mark.wuenschel@noaa.gov>
  
**Public availability statement**: Source data are publicly available.

## Methods

The forage fish energy denisty indicator comes from a collaborative project between UMASS Dartmouth Biology Department (Dr. Ken Oliveira, M.S student Kelcie Bean) and NEFSC Population Biology Branch (Mark Wuenschel).  The study focuses on evaluating energy content of the species in Table \@ref(tab:foragefish).

```{r foragefish, eval = T, echo = F}

forage.tab <- data.frame('Common Name' = c('Atlantic Herring','alewife','silver hake',
                                           'butterfish','northern sandlance','Atlantic mackerel',
                                           'longfin squid','northern shortfin squid'),
                         'Scientific Name' = c('*Clupea harengus*', '*Alosa pseudoharengus*',
                                        '*Merluccius bilinearis*', '*Peprilus triacanthus*', 
                                        '*Ammodytes dubius*','*Scomber Scombrus*', 
                                        '*Loligo pealeii*', '*Illex illecebrosus*'))
names(forage.tab) <- c("Common Name","Scientific Name")


knitr::kable(forage.tab, caption = "List of forage fish study species.",  booktabs=T) #%>%
 # kableExtra::kable_styling(full_width = F)
```

### Data sources
NEFSC spring and fall bottom trawl surveys. 

### Data extraction
NA 

### Data analysis

Samples were analyzed for proximate composition and energy density from NEFSC spring and fall bottom trawl surveys. Predictive relationships between the percent dry weight of samples and energy density were developed, and samples collected from current surveys are currently being analyzed for percentage dry weight to enable estimation of energy content (@Bean2020). The energy density of forage species differed from prior studies in the 1980s and 1990s (@steimle1985, @lawson1998, Table \@ref(tab:foragefish)).

Sampling and laboratory analysis is ongoing, with the goal of continuing routine monitoring of energy density of these species. 

### Data processing

Code for building the table used in the SOE can be found 
[here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_forage_energy_density.R).

**catalog link**
<https://noaa-edab.github.io/catalog/energy_density.html>