# Community Social Vulnerability Indicators (CSVI) {#engagement}

**Description**: The data here consist of two sources; 1) Port Commercial Fishing Activity Indicator scores which is comprised of commercial fishing landings and permit data from 2007 through 2024 summarized to indicate port-level activity in commercial fishing. 2) Community Social Vulnerability Indicators (CSVI) generated from 2023 American Community Survey 5-yr estimates Dataset in the U.S. Census American Community Survey (ACS) for coastal communities at the Census Designated Place or County Subdivision level.

Note, the Mid-Atlantic analysis for the PCFA Indicator does not include data from North Carolina (NC) given delays in receiving data from the Southeast region. NC ports land a significant portion of fish from Southeast managed species and thus, we elected to not include NC to avoid the risk of underestimation.

**Found in**: State of the Ecosystem - New England (2018+), State of the Ecosystem - Mid-Atlantic (2018+), State of the Ecosystem - Indicator Catalog (2024+)

**Indicator category**: Published methods; Extensive analysis, not yet published

**Contributor(s)**: Robert Murphy, Changhua Weng, Tanya Noteva
  
**Data steward**: Robert Murphy <robert.murphy@noaa.gov>

**Point of contact**: Robert Murphy <robert.murphy@noaa.gov>
  
**Public availability statement**: Source data are NOT publicly available. Please email Robert Murphy <robert.murphy@noaa.gov> for further information and queries of fishing and vulnerability indicator source data.
  
## Methods

### Data sources

NOAA Fisheries’ Community Social Vulnerability Indicators (CSVIs) utilized in this report were developed using secondary data including social and demographic variables downloaded from the 2023 American Community Survey (ACS) 5-yr estimates Dataset in the U.S. Census American Community Survey (ACS) for coastal communities at the Census Designated Place (CDP) level, and in some cases the County Subdivision (MCD) level. Commercial fisheries data used for the new composite Port Commercial Fishing Activity Indicator were pulled from the CAMS server located at Northeast Fisheries Science Center in Woods Hole, MA.

### Data analysis

The CSVIs were developed using the methodology described in @jacob_exploring_2010, @jacob_development_2013, @colburn_social_2012 and @jepson_development_2013. These indicators were constructed through principal component analysis with a single factor solution, and the following criteria had to have been met: a minimum variance explained of 45%; Kasier-Meyer Olkin measure of sampling adequacy above 0.500; factor loadings above 0.350; Bartlett’s test of sphericity significance above 0.05; and an Armor’s Theta reliability coefficient above 0.500. Factor scores for each community were ranked based on standard deviations into the following categories: High (>=1.00SD), Medium-High 0.500-0.999 SD), Medium (0.000-0.499 SD) and Low (<0.000 SD).

The new Port Commercial Fishing Activity Indicator uses the same suite of variables from the previous CSVI fisheries engagement indicator; the number of commercial fishing permits, the number of permitted dealers, the pounds of landed fish, and the value of landed fish. Instead of conducting an annual Principal Components Analysis, this new method simply normalizes each column of data (across all years) using a min-max scaling approach (range = 0 – 1) and then takes the mean of each column to create a composite average score for each port by year. Note, the value of landed fish data is first normalized by year to account for inflation over time. The PCFA analysis is conducted for each region (MA and NE) separately such that scores are comparable within region only.

### Data processing

Commercial fisheries data was pulled from the NEFSC CAMS database on Oracle and processed using R.

**catalog link**
<https://noaa-edab.github.io/catalog/engagement.html>