# Forage Fish Energy Density

**Description**: Forage Engery Density indicators

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2020), State of the Ecosystem - Mid-Atlantic (2020)

**Indicator category**: 

**Contributor(s)**: Mark Wuenschel, Ken Oliveira and Kelcie Bean
  
**Data steward**: Mark Wuenschel <mark.wuenschel@noaa.gov>
  
**Point of contact**: Mark Wuenschel <mark.wuenschel@noaa.gov>
  
**Public availability statement**: Source data are publicly available.

## Methods

A collaborative project between UMASS Dartmouth Biology Department (Dr. Ken Oliveira, M.S student Kelcie Bean) and NEFSC Population Biology Branch (Mark Wuenschel) is underway to evaluate energy content of forage species. The study focuses on the following species; Atlantic herring, alewife, silver hake, butterfish, northern sandlance, Atlantic mackerel, longfin squid, and northern shortfin squid. Samples have been analyzed for proximate composition and energy density from 2017 and 2018 NEFSC spring and fall bottom trawl surveys (Bean 2019, table below). Predictive relationships between the percent dry weight of samples and energy density were developed, and samples collected from 2019 surveys are currently being analyzed for percentage dry weight to enable estimation of energy content. The energy density of forage species differed from prior studies in the 1980s and 1990s (@steimle1985, @lawson1998). 

### Data sources
2017 and 2018 NEFSC spring and fall bottom trawl surveys. 

### Data extraction 


### Data analysis
Sampling and laboratory analysis is ongoing, with the goal of continuing routine monitoring of energy density of these species. 

### Data processing

Code for building the table used in the SOE can be found 
[here](https://github.com/NOAA-EDAB/ecodata/blob/master/chunk-scripts/macrofauna.Rmd-forage.R). 

Error: Names must be unique.
Backtrace:
     █
  1. ├─bookdown::render_book("index.Rmd", "bookdown::gitbook")
  2. │ └─bookdown:::render_cur_session(...)
  3. │   └─rmarkdown::render(...)
  4. │     └─knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. │       └─knitr:::process_file(text, output)
  6. │         ├─base::withCallingHandlers(...)
  7. │         ├─knitr:::process_group(group)
  8. │         └─knitr:::process_group.block(group)
  9. │           └─knitr:::call_block(x)
 10. │             └─knitr:::block_exec(params)
 11. │               ├─knitr:::in_dir(...)
 12. │               └─knitr:::evaluate(...)
 13. │                 └─evaluate::evaluate(...)
 14. │                   └─evaluate:::evaluate_call(...)
 15. │                     ├─evaluate:::timing_fn(...)
 16. │                     ├─base:::handle(...)
 17. │                     ├─base::withCallingH



# ```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/macrofauna.Rmd-forage.R"), echo = F, eval = T, warning = F, message=F}
# 
# ```
