# Habitat Diversity {#habitat_diversity}

**Description**: Species richness was derived from the Northeast Regional Habitat Assessment models for 55 common species sampled by the 2000-2019 spring and fall NEFSC bottom trawl surveys. The joint species distribution model controls for differences in capture efficiency across survey vessels.
 

**Indicator category**: Extensive analysis

**Found in**: State of the Ecosystem - New England (2023), 
State of the Ecosystem - Mid-Atlantic (2023) 

**Contributor(s)**: Chris Haak <ChrisHaak@gmail.com>
  
**Data steward**: Laurel Smith <laurel.smith@noaa.gov>
  
**Point of contact**: Laurel Smith <laurel.smith@noaa.gov>
  
**Public availability statement**: This analysis is based on NEFSC bottom trawl survey data which are publicly available. Please reached out to Laurel Smith with questions.


## Methods


### Data sources

Abundance data were extracted from the NEFSC’s SVDBS database using Survdat for 55 fish species regularly sampled on spring and fall NEFSC bottom trawl surveys:

Species included in NRHA Diversity Index: 


| Common Name             | Scientific Name                   |
|-------------------------|-----------------------------------|
| Acadian Redfish         | *Sebastes fasciatus*              |
| Alewife                 | *Alosa pseudoharengus*            |
| American Lobster        | *Homarus americanus*              |
| American Plaice         | *Hippoglossoides platessoides*    |
| American Shad           | *Alosa sapidissima*               |
| Atlantic Cod            | *Gadus morhua*                    |
| Altantic Croaker        | *Micropogonias undulatus*         |
| Atlantic Herring        | *Clupea harengus*                 |
| Atlantic Mackerel       | *Scomber scombrus*                |
| Barndoor Skate          | *Dipturus laevis*                 |
| Black Sea Bass          | *Centropristis striata*           | 
| Blackbelly Rosefish     | *Helicolenus dactylopterus*       |
| Blueback Herring        | *Alosa aestivalis*                |
| Bluefish                | *Pomatomus saltatrix*             |
| Butterfish              | *Peprilus triacanthus*            |
| Chain Dogfish           | *Scyliorhinus retifer*            |
| Clearnose Skate         | *Rostroraja eglanteria*           |
| Fawn Cusk Eel           | *Lepophidium profundorum*         |
| Fourbeard Rockling      | *Enchelyopus cimbrius*            |
| Fourspot Flounder       | *Hippoglossina oblonga*           |
| Goosefish               | *Lophius americanus*              |
| Gulf Stream Flounder    | *Citharichthys arctifrons*        |
| Haddock                 | *Melanogrammus aeglefinus*        |
| Horseshoe Crab          | *Limulus polyphemus*              |
| Jonah Crab              | *Cancer borealis*                 |
| Little Skate            | *Leucoraja erinaceus*             |
| Longfin Squid           | *Doryteuthis (Amerigo) pealeii*   |
| Longhorn Sculpin        | *Myoxocephalus octodecemspinosus* |
| Northern Searobin       | *Prionotus carolinus*             |
| Northern Shortfin Squid | *Illex illecebrosus*              |
| Northern Shrimp         | *Pandalus borealis*               |
| Ocean Pout              | *Zoarces americanus*              |
| Offshore Hake           | *Merluccius albidus*              |
| Pollock                 | *Pollachius pollachius*           |
| Red Hake                | *Urophycis chuss*                 |
| Rosette Skate           | *Leucoraja garmani*               |
| Scup                    | *Stenotomus chrysops*             |
| Sea Raven               | *Hemitripterus americanus*        |
| Sea Scallop             |  *Placopecten magellanicus*       |
| Silver Hake             | *Merluccius bilinearis*           |
| Smooth Dogfish          | *Mustelus canis*                  |
| Smooth Skate            | *Malacoraja senta*                |
| Spiny Dogfish           | *Squalus acanthias*               |
| Spot                    | *Leiostomus xanthurus*            |
| Spotted Hake            | *Urophycis regia*                 |
| Striped Searobin        | *Prionotus evolans*               |
| Summer Flounder         | *Paralichthys dentatus*           |
| Thorny Skate            | *Amblyraja radiata*               |
| Weakfish                | *Cynoscion regalis*               |
| White Hake              | *Urophycis tenuis*                |
| Windowpane Flounder     | *Scophthalmus aquosus*            |
| Winter Flounder         | *Pseudopleuronectes americanus*   |
| Winter Skate            | *Leucoraja ocellata*              |
| Witch Flounder          | *Glyptocephalus cynoglossus*      |
| Yellowtail Flounder     | *Myzopsetta ferruginea*           |




Data were converted to presence/absence for species richness modeling.

### Data analysis

#### Species Richness 

Estimated species richness is the number of unique species expected to be observed in NEFSC bottom trawl surveys conducted in a given ecological production unit (EPU) and year, based on a fitted joint-species distribution/habitat suitability model (considering only the 55 commonly-occurring species listed above).

 
#### Model Fitting


A spatiotemporal joint species distribution model was fitted to n=13231 observations of presence/absence in the Spring and Fall NEFSC bottom trawl surveys for the years 2000-2019, using the [Community Level Basis Function Model (CBFM) framework](https://github.com/fhui28/CBFM) with a binomial error distribution and logistic link function.  The probability of presence was modeled as a function of environmental predictor variables (using smooth terms), a vessel effect (factor) to account for changes in sampling gear, as well as spatiotemporal (Lat, Lon, Month) and temporal (Year) random effects, which were estimated hierarchically through a set of species-common basis functions. The model thus controls for differences in capture efficiency across survey vessels, permitting predictions on a common scale (here calibrated to the RFV Albatross IV).

#### Environmental Covariates

Covariate values (i.e., environmental parameters) corresponding to the approximate location (and time, when applicable) of each observation (i.e., tow) were extracted from the following sources:
Monthly mean surface and bottom temperature, surface and bottom salinity, and sea surface height anomaly were obtained from the GLORYS12V1 reanalysis (@Lellouche2012), as were annual minimum and maximum surface and bottom temperatures.

Monthly mean underwater optical parameters, including the intensity (photosynthetically active radiation - PAR) and spectral composition (hue angle) of downwelling light at mid-water column, were estimated from remote sensing data, following the methods of @Lee2005 and @Lee2022, respectively.

Hydrodynamic stress near the seabed (95th quantile) was obtained from the USGS Sea Floor Stress and Sediment Mobility database (Dalyander et al. 2012).


Annually-integrated chlorophyll was obtained from the Oceancolour-CCI (version 5) release (https://www.oceancolour.org/).

Bathymetric position index (BPI), benthic structural complexity, and sediment type data were estimated following the methods described at: https://www.conservationgateway.org/ConservationByGeography/NorthAmerica/UnitedStates/edc/reportsdata/marine/namera/namera/Pages/default.aspx/

#### Estimating Richness

Simulating from the fitted model, we generated 100 random draws of “joint” predictions of the species assemblage observed in the survey, taking into account species residual covariances (see @Wilkinson2021 for additional details). We used these to produce estimates of the mean species richness (and corresponding 95% prediction intervals) across all observations within each ecological production unit (EPU) for each modeled year (2000-2019).



### Data Processing

The Habitat Diversity indicator was formatted for inclusion in the `ecodata` R package with the code found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_habitat_diversity.R).