# Harbor Porpoise Bycatch {#harborporpoise}


**Description**: Harbor Porpoise Bycatch Indicator

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2018+), State of the Ecosystem - Mid-Atlantic (2018+)

**Indicator category**: Synthesis of published information; Published methods

**Contributor(s)**: Kristin Precoda, Christopher D. Orphanides, Debra Palka
  
**Data steward**: Debra Palka <debra.palka@noaa.gov>

**Point of contact**: Debra Palka <debra.palka@noaa.gov>

**Public availability statement**: Source data are available in public [stock assessment reports](https://www.fisheries.noaa.gov/national/marine-mammal-protection/marine-mammal-stock-assessment-reports-region).
  

## Methods


### Data sources
Bycatch estimates and potential biological removal levels are reported in the publicly available [Marine Mammal Stock Assessment reports](https://www.fisheries.noaa.gov/national/marine-mammal-protection/marine-mammal-stock-assessment-reports-region). More descriptions on data sources, processing and analyses are found in Northeast Fisheries Science Center (NEFSC) Center Reference Documents (CRDs) and journal papers. The data to calculate the bycatch estimate comes from observer program databases and fishing effort databases.


### Data extraction 
Annual and 5-year averaged bycatch estimates are documented in Center Reference Documents (CRD). The potential biological removal values are extracted from the Stock Assessment Reports. 

### Data analysis
Bycatch estimates and their associated coefficients of variation are documented in the CRDs, then reported in the Marine Mammal Stock Assessment Reports. Annual estimates from all fisheries as reported in the Marine Mammal Stock Assessment Reports are summed together and the CV of the sum is calculated using the delta method. The 95% confidence intervals are then calculated from the sums and associated CVs assuming a lognormal distribution. ($\sigma = \mu CV$; $CI = \bar{x} \pm \sigma * 1.96$).

Data were analyzed and formatted for inclusion in the `ecodata` R package using the R code found here, [Harbor Porpoise](https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/data-raw/get_harborporpoise.R).

**catalog link**
<https://noaa-edab.github.io/catalog/harborporpoise.html>