# Marine Heatwave {#heatwave}

**Description**: Marine Heatwave

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2020+), Mid-Atlantic (2020+)

**Indicator category**: Published methods, Database pull with analysis

**Contributor(s)**: Vincent Saba
  
**Data steward**: Brandon Beltz <Brandon.Beltz@noaa.gov>
  
**Point of contact**: Brandon Beltz <Brandon.Beltz@noaa.gov>
  
**Public availability statement**: Source data are publicly available. Please email vincent.saba@noaa.gov for further information and queries of the marine heatwave indicator data.

## Methods

Marine heatwaves (MHWs) measure not just anomalously high temperature, but how long the ecosystem is subjected to the high temperature. They are driven by both atmospheric and oceanographic factors and can have dramatic impacts on marine ecosystems. Marine heatwaves are measured in terms of intensity (water temperature) and duration (the cumulative number of degree days) using measurements of sea surface temperature (surface MHWs) or a combination of observations and models of bottom temperature (bottom MHWs). 

**2023-**

Recent research by @jacox_thermal_2020 and @jacox_global_2022 have modified the MHW methodology originally developed by @hobday_hierarchical_2016.  

The new MHW indices use the entire temperature time-series for the baseline climatology (e.g. 1982-2022 in the 2023 report) and the global warming trend is removed (i.e. we detrended the data to create a shifting baseline instead of a fixed baseline) .  This new MHW method allows us to discern true extreme events from long-term ocean warming (climate change).  Surface MHW events are based on the criteria of a warming event that lasts for five or more days with temperatures above the 90th percentile of the historical daily climatology (1982-2022).  Bottom MHW events are defined as a warming event that lasts for thirty or more days with bottom temperatures above the 90th percentile of the historical daily climatology (1982-2022).  The longer time period criterion for bottom temperature is due to the longer persistence time of ocean bottom temperature anomalies in the U.S. northeast shelf (@chen_seasonal_2021).  

The new MHW indices can now discern extreme events that truly are “extreme” rather than occupying most of the year as was the case in the Gulf of Maine in 2021 using previous methods.  Because this approach moves from a fixed baseline to a shifting baseline by detrending ocean temperature data and using the entire time-series as a climatology, the global warming signal is removed and thus we are left with extremes in the variability of ocean temperature.  A combination of long-term ocean warming and MHWs should be used to assess total heat stress on marine organisms.

**2020-2022**

Marine heatwave (surface only) analysis for Georges Bank, Gulf of Maine, and the Middle Atlantic Bight according to the definition in @hobday_hierarchical_2016.  

### Data sources

[NOAA high-res OISST (daily, 25-km, 1982-2019)](https://www.esrl.noaa.gov/psd)

Marine heatwave analysis for Georges Bank, Gulf of Maine, and the Middle Atlantic Bight according to the definition in @hobday_hierarchical_2016.  Heatwaves are defined as temperatures that exceed the 90th percentile for at least 5 consecutive days for surface heatwaves and at least 30 consecutive days for bottom heatwaves. 


### Data extraction 

Each yearly file (global) was downloaded, concatenated into a single netcdf file using nco (Unix), and then cropped to the USNES region using Ferret.  Each EPU's time-series of SST was averaged using .shp file boundaries for the MAB, GB, and GOM (also done in Ferret) and saved to the three .csv files.

### Data analysis

**2023-** Maximum Intensity and Duration - Number of Days in a heatwave state (N days) are calculated using NOAA OISST daily sea surface temperature data (25-km resolution) from January 1982 to December of the most recent year. The heatwaves are calculated based on the algorithms in Hobday et al. 2016 and by using a climatology of 1982-most recent year.  These metrics were run R using https://robwschlegel.github.io/heatwaveR/.

**2020-2022**
The marine heatwave metrics Maximum Intensity [deg. C] and Cumulative Intensity [deg. C x days] are calculated using NOAA OISST daily sea surface temperature data (25-km resolution) from January 1982 to December 2019.  The heatwaves are calculated based on the algorithms in Hobday et al. 2016 and by using a climatology of 1982-2011.  These metrics were run R using https://robwschlegel.github.io/heatwaveR/.


### Data processing 

Marine Heatwave data were formatted for inclusion in the `ecodata` R package using this [R code](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_heatwave.R).

**catalog link**
<https://noaa-edab.github.io/catalog/heatwave.html>
<https://noaa-edab.github.io/catalog/heatwave_year.html>