# Atlantic Highly Migratory Species Pelagic Observer Program CPUE {#hms_cpue}

**Description**: CPUE from pelagic observer program (POP) observed hauls, presented as number of fish per haul, is provided for the northeast (i.e., the Northeast Coastal and Mid-Atlantic Bight fishing areas) by year/species from 1992-2023.

**Indicator category**: Database pull with analysis

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2021+), State of the Ecosystem - Mid-Atlantic (2021+), State of the Ecosystem - Indicator Catalog (2024+)

**Contributor(s)**: Jennifer Cudney, Tobey Curtis, Daniel Daye
  
**Data steward**:  Jennifer Cudney, Tobey Curtis, Daniel Daye
  
**Point of contact**:  Jennifer Cudney <jennifer.cudney@noaa.gov>
  
**Public availability statement**: Source data are NOT publicly available. Pelagic observer data is considered confidential data, and must be screened to ensure that data meet requirements for "rule of three" at the set and vessel level before they can be distributed. 


## Methods

### Data sources
Data for this indicator are sourced from the NOAA Southeast Fisheries Science Center, Pelagic Observer Program. These data come from the NOAA Southeast Fisheries Science Center databases holding the Atlantic highly migratory species information from the pelagic observer program. 

The Southeast Pelagic Observer Program monitors the pelagic longline fleet all along the Northeast U.S. Shelf. This covers approximately 1000 hauls per year and targets 8% coverage of the fishing effort. 


### Data analysis

Catch per unit effort was calculated as number of individuals per haul and summarized by year and species. 

The species groupings are available in the table below. 

| Category       | Common Name          | Species Name                 |
|----------------|----------------------|------------------------------|
| Small Coastal  | Atlantic Sharpnose   | *Rhizoprionodon terraenovae* |
| Small Coastal  | Blacknose            | *Carcharhinus acronotus*     |
| Small Coastal  | Bonnethead           | *Sphyrna tiburo*             |
| Small Coastal  | Finetooth            | *Carcharhinus isodon*        |
| Large Coastal  | Blacktip             | *Carcharhinus limbatus*      |  
| Large Coastal  | Bull                 | *Carcharhinus leucas*        |
| Large Coastal  | Great Hammerhead     | *Sphyrna mokarran*           |
| Large Coastal  | Lemon                | *Negaprion brevirostris*     |
| Large Coastal  | Nurse                | *Ginglymostoma cirratum*     |
| Large Coastal  | Sandbar              | *Carcharhinus plumbeus*      |
| Large Coastal  | Scalloped Hammerhead | *Sphyrna lewini*             |
| Large Coastal  | Silky                | *Carcharhinus falciformis*   |
| Large Coastal  | Smooth Hammerhead    | *Sphyrna zygaena*            | 
| Large Coastal  | Spinner              | *Carcharhinus brevipinna*    |
| Large Coastal  | Tiger                | *Galeocerdo cuvier*          |
| Prohibited     | Atlantic Angel       | *Squatina dumeril*           |
| Prohibited     | Basking              | *Cetorhinus maximus*         |
| Prohibited     | Bigeye Thresher      | *Alopias superciliosus*      |
| Prohibited     | Bignose              | *Carcharhinus altimus*       |
| Prohibited     | Night                | *Carcharhinus signatus*      |
| Prohibited     | Sand Tiger           | *Carcharias taurus*          |
| Prohibited     | Sevengill            | *Notorynchus cepedianus*     |
| Prohibited     | Sixgill              | *Hexanchus griseus*          |
| Prohibited     | White                | *Carcharodon carcharias*     |
| Pelagic        | Blue                 | *Prionace glauca*            |
| Pelagic        | Dusky                | *Carcharhinus obscurus*      |
| Pelagic        | Oceanic Whitetip     | *Carcharhinus longimanus*    |
| Pelagic        | Porbeagle            | *Lamna nasus*                |
| Pelagic        | Shortfin Mako        | *Isurus oxyrinchus*          |
| Pelagic        | Thresher             | *Alopias vulpinus*           |

### Data processing 
HMS staff sent a request for data to POP Observer Program staff (Sascha Cushner, Lawrence Beerkircher, Garry Decossas, and Scott Leach) using this form (https://forms.gle/kiMGRfUwbKJCf8Vs6). SEFSC statistician Garry Decossas completed the data pull based on submissions to the SOE from previous years, and provided the data to HMS staff. Data from the areas (MAB, NEC) and time period of interest (1992-2023) are summarized by species and year. Number of hauls per year are also provided to enable CPUE calculations of species per year. This is a data pull of ALL species reported in these areas, so there is more than just sharks in the dataset.

Code used to process this data for SOE products can be found on Github - [NOAA-EDAB/ecodata](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_hms_cpue.R).

**catalog link**
<https://noaa-edab.github.io/catalog/hms_cpue.html>