# Harbor Porpoise Bycatch

```{r,  echo = F, message=F}

#Load packages
library(knitr)
library(rmarkdown)

```

**Description**: Harbor Porpoise Indicator

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2018, 2019), State of the Ecosystem - Mid-Atlantic (2018, 2019)

**Indicator category**: Synthesis of published information; Published methods

**Contributor(s)**: Christopher D. Orphandies
  
**Data steward**: Chris Orphanides, <chris.orphanides@noaa.gov>

**Point of contact**: Chris Orphanides, <chris.orphanides@noaa.gov>

**Public availability statement**: Source data are available in public [stock assessment reports](https://www.fisheries.noaa.gov/national/marine-mammal-protection/marine-mammal-stock-assessment-reports-region) (2018 report in-press). Derived data as shown in the 2018 SOE reports are available [here](http://comet.nefsc.noaa.gov/erddap/tabledap/protected_species_soe_v1.html)
  

## Methods


### Data sources
Reported harbor porpoise bycatch estimates and potential biological removal levels can be found in publicly available documents; detailed [here](https://www.fisheries.noaa.gov/national/marine-mammal-protection/marine-mammal-stock-assessment-reports-region). The most recent bycatch estimates for 2016 were taken from the 2018 stock assessment (in-press). More detailed documentation as to the methods employed can be found in NOAA Fisheries Northeast Fisheries Science Center (NEFSC) Center Reference Documents (CRDs) found on the NEFSC [publications page](https://www.nefsc.noaa.gov/publications/crd/). 

The document for the 2016 estimates (CRD 19-04) is available [here](https://www.nefsc.noaa.gov/publications/crd/crd1904/crd1904.pdf). Additional methodological details are available for previous year's estimates and are documented in numerous published CRDs: [CRD 17-18](https://www.nefsc.noaa.gov/publications/crd/crd1718/crd1718.pdf), [CRD-16-05](https://www.nefsc.noaa.gov/publications/crd/crd1605/crd1605.pdf), [CRD 15-15](https://www.nefsc.noaa.gov/publications/crd/crd1515/crd1515.pdf), [CRD 14-02](https://repository.library.noaa.gov/view/noaa/4718), [CRD 13-13](https://www.nefsc.noaa.gov/publications/crd/crd1313/crd1313_2nd_ed.pdf), [CRD 11-08](https://www.nefsc.noaa.gov/publications/crd/crd1108/1108.pdf), [CRD 10-10](https://www.nefsc.noaa.gov/publications/crd/crd1010/crd1010.pdf), [CRD 07-20](https://www.nefsc.noaa.gov/publications/crd/crd0720/crd0720.pdf), [CRD 06-13](https://www.nefsc.noaa.gov/publications/crd/crd0613/crd0613.pdf), [CRD 03-18](https://www.nefsc.noaa.gov/publications/crd/crd0318/crd0318.pdf), [CRD 01-15](https://www.nefsc.noaa.gov/publications/crd/crd0115/0115.pdf), and [CRD 99-17](https://www.nefsc.noaa.gov/publications/crd/pdfs/crd9917.pdf).

### Data extraction 
Annual gillnet bycatch estimates are documented in a CRD (see sources above). These feed into the Stock Assessment Reports which report both the annual bycatch estimate and the mean 5-year estimate. The 5-year estimate is the one used for management purposes, so that is the one provided for the SOE plot.

### Data analysis
Bycatch estimates as found in stock assessment reports were plotted along with confidence intervals. The confidence intervals were calculated from published CVs assuming a normal distribution ($\sigma = \mu CV$; $CI = \bar{x} \pm \sigma * 1.96$).

Data were analyzed and formatted for inclusion in the `ecodata` R package using the R code found [here](https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/data-raw/get_harborporpoise.R).


### Plotting
 Code used to plot harbor porpoise data can be found [here](https://github.com/NOAA-EDAB/tech-doc/tree/master/R/stored_scripts/hp_indicator_plotting.R)


