# Mid-Atlantic Harmful Algal Bloom Indicator

```{r, echo = F, message=F}

#Load packages
library(knitr)
library(rmarkdown)

```

**Description**: An aggregation of reported algal bloom data in Chesapeake Bay between 2007-2017.

**Found in**: State of the Ecosystem - Mid-Atlantic (2018)

**Indicator category**: Database pull

**Contributor(s)**: Sean Hardison, Virginia Department of Health

**Data steward**: Kimberly Bastille, <kimberly.bastille@noaa.gov>

**Point of contact**: Kimberly Bastille, <kimberly.bastille@noaa.gov>

**Public availability statement**: Source data for this indicator are available [here](https://github.com/NOAA-EDAB/tech-doc/tree/master/data/CB_HAB). Processed time series can be found [here](http://comet.nefsc.noaa.gov/erddap/tabledap/CBhabs_ann_soe_v2.html).


## Methods
We presented two indicator time series for reports of algal blooms in the southern portion of Chesapeake Bay between 2007-2017. The first indicator was observations of algal blooms above 5000 cell ml^-1^. This threshold was developed by the Virginia Department of Health (VDH) for *Microcystis* spp. algal blooms based on World Health Organization guidelines [@WHO2003; @VDH2011].  VDH also uses this same threshold for other algal species blooms in Virginia waters. When cell concentrations are above 5000 cell ml^-1^, VDH recommends initiation of biweekly water sampling and that relevant local agencies be notified of the elevated cell concentrations.

The second indicator we reported, blooms of *Cochlodinium polykrikoides* at cell concentrations >300 cell ml^-1^, was chosen due to reports of high ichthyotoxicity seen at these levels. @Tang2009 showed that fish exposed to cultured *C. polykrikoides* at densities as low 330 cells ml^-1^ saw 100% mortality within 1 hour, which if often far less than *C. polykrikoides* cell concentrations seen in the field. Algal bloom data were not available for 2015 nor 2010. The algal bloom information presented here are a synthesis of reported events, and has been updated to include data not presented in the 2018 State of the Ecosystem Report. 

### Data sources
Source data were obtained from VDH. Sampling, identification, and bloom characterization was completed by the VDH, Phytoplankton Analysis Laboratory at Old Dominion University (ODU), Reece Lab at the Virginia Institute of Marine Science (VIMS), and Virginia Department of Environmental Quality. Problem algal species were targeted for identification via light microscopy followed by standard or quantitative PCR assays and/or enzyme-linked immunosorbent assay (ELISA). Reports specifying full methodologies from ODU, VIMS, and VDH source data are available upon request.

### Data extraction
Data were extracted from a series of spreadsheets provided by the VDH. We quantified the number of algal blooms in each year reaching target cell density thresholds in the southern Chesapeake Bay.

(ref:r-extract) All reported algal blooms >5000 cells ml ^-1^ (black), and reports of *C. polykrikoides* blooms >300 cells ml ^-1^ (red) between 2007-2017.

R code used in extracting harmful algal bloom data can be found [here](https://github.com/NOAA-EDAB/tech-doc/tree/master/R/stored_scripts/mab_hab_extraction.R).


### Data analysis
<!--Text description of analysis methods, similar in structure and detail to a peer-reviewed paper methods section-->
No data analysis steps took place for this indicator.