# Inshore survey (Massachusetts) {#mass_inshore_survey}

**Description**: Massachusetts Division of Marine Fisheries Bottom Trawl Survey

**Indicator category**: Database pull with analysis

**Found in**: State of the Ecosystem - Mid-Atlantic (2019+), State of the Ecosystem - New England (2019+)

**Contributor(s)**: Andrew Beet, Sean Lucey
  
**Data steward**: Andrew Beet <andrew.beet@noaa.gov>
  
**Points of contact**: Andrew Beet <andrew.beet@noaa.gov>
  
**Public availability statement**: Data are available upon request. 

## Methods

### Data sources

Mass Inshore bottom trawl survey data sets were derived from raw survey data. Data from the Massachusetts Inshore Bottom Trawl Survey are stored on local servers at the Northeast Fisheries Science Center (Woods Hole, MA), and are also available upon request. More information about the Massachusetts Inshore Bottom Trawl Survey is available [here](https://www.mass.gov/service-details/review-trawl-survey-updates).

### Data extraction

Source data from the Massachusetts DMF Bottom Trawl Survey were pulled using the function [`survdat::get_mass_inshore_survey_data()`](https://noaa-edab.github.io/survdat/reference/get_mass_inshore_survey_data.html) form the R package [`survdat`](https://noaa-edab.github.io/survdat/index.html). 

### Data analysis

Biomass indices were provided as stratified mean biomass (kg `r ifelse(knitr::is_latex_output(), 'tow\\textsuperscript{-1}', 'tow<sup>-1</sup>')`). Time series of stratified mean biomass were calculated through the following procedure:

1. All species catch weights were summed for each tow and for each feeding guild category. 
2. The average weight per tow, associated variances and standard deviation for each survey, region, stratum, and feeding guild was calculated.
3. Stratified mean biomass was then calculated as the sum of the weighted averages of the strata, where the weight of a given [stratum](https://nefsc.github.io/NEFSC-Spatial/reference/mass_inshore_strata.html) was the proportion of the survey area accounted for by that stratum. 

These calculations followed those used to find stratified mean biomass by feeding guild in the NEFSC Bottom Trawl Survey and are described in greater detail in the [Survey Data](#survdat) section.

**catalog link**
<https://noaa-edab.github.io/catalog/mass_inshore_survey.html>