# Harmful Algal Bloom Indicator - New England

**Description**: Regional incidence of shellfish bed closures due to presence of toxins associated with harmful algae. 

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2018)

**Indicator Category**: Synthesis of published information

**Contributor(s)**: Dave Kulis, Donald M Anderson, Sean Hardison

**Data steward**: Kimberly Bastille, <kimberly.bastille@noaa.gov>

**Point of contact**: Kimberly Bastille, <kimberly.bastille@noaa.gov>

**Public availability statement**: Data are publicly available (see Data Sources below).

## Methods
The New England Harmful Algal Bloom (HAB) indicator is a synthesis of shellfish bed closures related to the presence of HAB-associated toxins above threshold levels from 2007-2016 (Figure \@ref(fig:NE-HAB)). Standard detection methods were used to identify the presence of toxins associated with Amnesic Shellfish Poisoning (ASP), Paralytic Shellfish Poisoning (PSP), and Diarrhetic Shellfish Poisoning (DSP) by state and federal laboratories. 

#### Paralytic Shellfish Poisoning
The most common cause of shellfish bed closures in New England is the presence of paralytic shellfish toxins (PSTs) produced by the dinoflagellate *Alexandrium catenella*. All New England states except Maine relied on the Association of Official Analytical Chemists (AOAC) approved mouse bioassay method to detect PSTs in shellfish during the 2007-2016 period reported here [@Anonymous2005].

In Maine, PST detection methods were updated in May 2014 when the state adopted the hydrophilic interaction liquid chromatography (HILIC) UPLC-MS/MS protocol [@Boundy2015] in concordance with National Shellfish Sanitation Program (NSSP) requirements.  Prior to this, the primary method used to detect PST in Maine was with the mouse bioassay. 

#### Amnesic Shellfish Poisoning
Amnesic shellfish poisoning (ASP) is caused by the toxin domoic acid (DA), which is produced by several phytoplankton species belonging to the genus *Pseudo-nitzchia*. In New England, a UV-HPLC method [@Quilliam1995], which specifies a HPLC-UV protocol, is used for ASP detection. 

#### Diarrhetic Shellfish Poisoning
Diarrhetic Shellfish Poisoning (DSP) is rare in New England waters, but the presence of the DSP-associated okadaic acid (OA) in mussels was confirmed in Massachusetts in 2015 (J. Deeds, personal communication, July 7, 2018). Preliminary testing for OA in Massachusetts utilized the commercially available Protein Phosphatase Inhibition Assay (PPIA) and these results are confirmed through LC-MS/MS when necessary [@Smienk2012; @Stutts2017]. 


### Data sources
<!--Please provide a text description of data sources, inlcuding primary collection methods. What equipment was used to turn signal to data? From which vessel were data collected and how? What quality control procedures were employed, if any?--> 


Data used in this indicator were drawn from the 2017 Report on the ICES-IOC Working Group on Harmful Algal Bloom Dynamics (WGHABD). The report and data are available [here](http://www.ices.dk/sites/pub/Publication%20Reports/Expert%20Group%20Report/SSGEPD/2017/01%20WGHABD%20-%20Report%20of%20the%20ICES%20-%20IOC%20Working%20Group%20on%20Harmful%20Algal%20Bloom%20Dynamics.pdf).


Closure information was collated from information provided by the following organizations:
```{r closuresrc, echo = F, include = T, results='asis', message=FALSE, warning=F}
tabl <- data.frame(State = c("Maine","New Hampshire","Massachusetts","Rhode Island","Connecticut"),
                   `Source Organization` = c("Maine Department of Marine Resources",
                                           "New Hampshire Department of Environmental Services",
                                           "Massachusetts Division of Marine Fisheries",
                                           "Rhode Island Department of Environmental Management",
                                           "Connecticut Department of Agriculture"))
names(tabl)[2] <- "Source Organization"
knitr::kable(
  tabl, booktabs = TRUE,
  caption = 'Shellfish closure information providers.'
)

```


### Data extraction
<!--Text overview description of extraction methods. What information was extracted and how was it aggregated? Can point to other indicator extraction methods if the same.-->

Data were extracted from the original report visually and accuracy confirmed with report authors.


### Data analysis
<!--Text description of analysis methods, similar in structure and detail to a peer-reviewed paper methods section-->

No data analysis steps took place for this indicator.

### Plotting

The script used to develop the figure in the SOE report can be found [here](https://github.com/NOAA-EDAB/tech-doc/tree/master/R/stored_scripts/ne_hab_plotting.R).
