# Ocean Acidification and Other Stressors {#ocean_acidification}

**Description**: Maps and variability of regional carbonate chemistry and other oceanographic properties

**Indicator category**: Synthesis of published information, Database pull with analysis

**Found in:** State of the Ecosystem - Gulf of Maine & Georges Bank (2021+); State of the Ecosystem - Mid-Atlantic Bight (2021+), State of the Ecosystem - Indicator Catalog (2024+)

**Contributor(s)**: Grace Saba, Lori Garzio

**Data steward**: Grace Saba [saba\@marine.rutgers.edu](mailto:saba@marine.rutgers.edu){.email}

**Point of contact**: Grace Saba [saba\@marine.rutgers.edu](mailto:saba@marine.rutgers.edu){.email}

**Public availability statement**: Source data are publicly available (see Data Sources).

## Methods

The New England Fishery Management Council (NEFMC) and Mid-Atlantic Fishery Management Council (MAFMC) have recently requested regional Ocean Acidification (OA) information in the State of the Ecosystem reports. The work included in the State of the Ecosystem 2021 report, seasonal dynamics of pH in shelf waters in the Mid-Atlantic, was synthesized from Wright-Fairbanks et al. (2020). The maps included in the State of the Ecosystem 2022 reports include a plot of bottom pH in summer over the entire U.S. Northeast Shelf (2007-2021), and glider-based pH profiles during summer 2021 in both the Mid-Atlantic Bight (MAB) and the Gulf of Maine. The plots in the State of the Ecosystem 2023 reports included maps of bottom summer aragonite saturation (ΩArag, or omega) over the entire U.S. Northeast Shelf (2007-2022) and locations where summer bottom ΩArag reached lab-derived sensitivity levels of designated target species. The products developed for the State of the Ecosystem 2024 reports included: plots of the seasonal progression (Spring-Fall 2023) of oceanographic properties (including temperature, chlorophyll, dissolved oxygen, pH, and aragonite saturation state) on the New Jersey coastal shelf; plots summarizing a multi-stressor event in the Mid-Atlantic during summer 2023; static and animated maps of summer-time bottom pH and aragonite saturation state on the U.S. Northeast Shelf (2007-2023); and maps of locations where species sensitivity levels for aragonite saturation state were reached in bottom water during the summer (2007-2023).

The products developed for the State of the Ecosystem 2025 report includes: static and animated maps of seasonal surface and bottom pH and aragonite saturation state on the U.S. Northeast Shelf, and seasonal maps of locations where species sensitivity levels for aragonite saturation state were reached in bottom-waters within the species habitat depth range (winter 2012-2024, spring 2014-2024, summer 2007-2024, fall 2013-2023); and maps of bottom temperature anomalies, bottom aragonite saturation state and surface chlorophyll anomalies for the summers of 2022-2024.

Products from all State of the Ecosystem reports to date were developed using openly accessible, quality-controlled data from vessel-based discrete samples, glider-based measurements, satellite data products from the NASA Ocean Biology Distributed Active Archive Center (OB.DAAC), and the E.U. Copernicus Marine Service Information (CMEMS) Global Ocean Physics Reanalysis (GLORYS12V1) data product (see Data Sources), and data from published laboratory-based experimental studies (see Plotting).

### Data sources

Glider-based observations of pH (and other variables including temperature, salinity, chlorophyll-a, and dissolved oxygen) began in the southern MAB region in May 2018 (Saba et al. 2019), and seasonal glider pH missions thereafter began in February 2019 (Wright-Fairbanks et al. 2020; although no deployments occurred in 2020 as a result of the COVID pandemic). Simultaneous measurements from the glider's pH, temperature, and salinity sensors enable the derivation of total alkalinity and calculation of other carbonate system parameters including aragonite saturation state (ΩArag). The glider pH observation program expanded spatially and temporally, with additional deployments in the northern MAB (New York Bight) and the Gulf of Maine, starting in February 2021. A typical glider mission runs for about 4 weeks, covers 500 km, and collects data though the full water column.

For the historical seasonal surface and bottom-water pH and aragonite saturation state data synthesis (static and animated maps of seasonal surface and bottom pH and aragonite saturation state on the U.S. Northeast Shelf; and maps of seasonal bottom locations where species sensitivity levels for aragonite saturation state were reached):
- Full-resolution delayed-mode glider datasets are available on the [IOOS Glider DAC ERDDAP server](https://gliders.ioos.us/erddap/index.html). These datasets were QC'd by the deploying institution and pH was calculated from raw variables. Summarized data files containing combined bottom and surface pH and aragonite saturation state data from glider-based (and vessel-based, see below) measurements can be found [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/data_files/).
- Vessel-based data were mined from the [Coastal Ocean Data Analysis Product in North America, version v2021](https://essd.copernicus.org/articles/13/2777/2021/) (Jiang et al. 2021). This data product synthesizes two decades of quality-controlled inorganic carbon system parameters (including pH, total alkalinity, dissolved inorganic carbon) along with other physical and chemical parameters (temperature, salinity, dissolved oxygen, nutrients) collected from the North American continental shelves. Additionally, recent vessel-based datasets that were not included in CODAP-NA (Jiang et al. 2021) were included in this synthesis. These datasets were collected during more recent NOAA NEFSC Ecosystem Monitoring (EcoMon) surveys: June 2019 (Cruise ID HB1902), August 2019 (Cruise ID GU1902), October 2019 (Cruise ID GU1905), May 2021 (Cruise ID GU2102), August 2021 (Cruise ID PC2104), October 2021 (Cruise ID PC2106), June 2022 (Cruise ID HB2204), November 2022 (Cruise ID PC2205), June 2023 (Cruise ID HB2302), and the East Coast Ocean Acidification ECOA-3 Cruise (Cruise ID ECOA3). These datasets were downloaded via the [NCEI Ocean Carbon and Acidification Data Portal](https://www.ncei.noaa.gov/access/ocean-carbon-acidification-data-system-portal/). Resulting data files containing combined bottom and surface pH and aragonite saturation state data from vessel-based (and glider-based, see above) measurements can be found [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/data_files/).

For the maps of satellite-derived surface chlorophyll-a anomalies for summer 2022-2024, data were downloaded from the NASA Ocean Biology Distributed Active Archive Center (OB.DAAC) [Level 3 & 4 Browser](https://oceancolor.gsfc.nasa.gov/l3/).

For the maps of bottom temperature anomalies for summer 2022-2024, data were extracted from the E.U. Copernicus Marine Service Information (CMEMS) [Global Ocean Physics Reanalysis (GLORYS12V1)](https://data.marine.copernicus.eu/product/GLOBAL_MULTIYEAR_PHY_001_030/description) dataset.

### Data extraction

Glider data were processed and quality-controlled by the deploying institution and are available for download on the [IOOS Glider DAC ERDDAP server](https://gliders.ioos.us/erddap/index.html).

[CODAP-NA, Version 2021 data](https://www.ncei.noaa.gov/data/oceans/ncei/ocads/metadata/0219960.html) were accessed and downloaded on October 14, 2021. 

EcoMon datasets were accessed and downloaded on October 13, 2022 (Cruise IDs HB1902, GU1902, PC2104), November 17, 2023 (Cruise ID HB2204), and August 21, 2024 (Cruise IDs GU1905, GU2102, PC2106, PC2205, HB2302, ECOA3).

Monthly data files of SNPP-VIIRS satellite-derived chlorophyll data were downloaded from the NASA Ocean Biology Distributed Active Archive Center (OB.DAAC) [Level 3 & 4 Browser](https://oceancolor.gsfc.nasa.gov/l3/) on November 6, 2024 with the following selections:
- Product Status: Standard
- Instrument: SNPP-VIIRS
- Product: Chlorophyll concentration
- Period: Monthly
- Resolution: 4km
- Start Date: 2012-03-01
- End Date: 2024-08-31

Monthly data files of bottom temperature from the E.U. Copernicus Marine Service Information (CMEMS): [Global Ocean Physics Reanalysis (GLORYS12V1)](https://data.marine.copernicus.eu/product/GLOBAL_MULTIYEAR_PHY_001_030/description) dataset were downloaded on November 14, 2024 using the [Python Copernicus Marine Toolbox API](https://help.marine.copernicus.eu/en/articles/8283072-copernicus-marine-toolbox-api-subset)
- Dataset ID: cmems_mod_glo_phy_my_0.083deg_P1M-m: March 2012 to June 2021
- Dataset ID: cmems_mod_glo_phy_myint_0.083deg_P1M-m: July 2021 to August 2024

### Data processing

For MAB glider datasets, total alkalinity was calculated from salinity using a linear relationship determined from in situ water sampling data taken during glider deployment and recovery in addition to ship-based water samples (Wright-Fairbanks et al. 2020). For the Gulf of Maine glider datasets, total alkalinity (provided in the files) was calculated from salinity using the linear relationship (TA = 47.6 * salinity + 643.0) taken from Hunt et al 2021, figure 6, Historical regression for Gulf of Maine: https://doi.org/10.1016/j.marchem.2021.103960. Calculations for ΩArag were then conducted using PyCO2SYS (Humphreys et al. 2020) with inputs of pressure, temperature, salinity, total alkalinity, and pH. A table containing all glider deployments used in this analysis is available [here](https://github.com/lgarzio/cinar-soe/blob/master/analysis2025/glider_deployment_summary_2019_2024.csv).

Data from CODAP-NA v2021 were spatially limited to the U.S. Northeast Shelf. The resulting datasets included those from major vessel-based campaigns (East Coast Ocean Acidification, ECOA I and II cruises 2015 and 2018; The Gulf of Mexico and East Coast Carbon cruises, GOMECC 2007 and 2012; EcoMon 2012-2013, 2015-2019).

For vessel-based datasets, when ΩArag was unavailable it was calculated using PyCO2SYS (Humphreys et al. 2020) with inputs of pressure, temperature, salinity, total alkalinity, and pH.

Bottom water pH and ΩArag values were defined as the median of the measurements (or calculated ΩArag values) within the deepest 1m of a glider profile or, for vessel-based measurements, the deepest measurement of a vertical CTD/Rosette cast where water samples were collected, for profiles deeper than 10m. In order to validate whether the deepest depth was at or near the bottom, the sampling depth was compared to water column depth (when provided) or water depths extracted from a [GEBCO](https://www.gebco.net/data_and_products/gridded_bathymetry_data/) bathymetry grid based on the sample collection coordinates. Any glider profiles/vessel-based casts with the deepest measurement shallower than the bottom 20% of total water column depth were removed. This allowed for a sliding scale instead of providing a strict cut off (e.g., 1 m above the bottom). 

Surface water pH and ΩArag values were defined as the median of the measurements (or calculated ΩArag values) recorded at the top of a glider profile (between 2-4m depth) for profiles deeper than 10m or, for vessel-based measurements the shallowest measurement of a vertical CTD/Rosette cast where water samples were collected provided the measurement depth was <10m, or all of the surface measurements provided for underway datasets.

Resulting data files containing combined bottom and surface pH and aragonite saturation state data from glider- and vessel-based measurements can be found [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/data_files/).

Seasonal averages for chlorophyll and bottom temperature were calculated by averaging monthly data files according to the groupings below, and anomalies were calculated as the difference from the mean (2012-2024).
- Winter: December, January, February
- Spring: March, April, May
- Summer: June, July, August
- Fall: September, October, November

### Plotting

A set of plots was constructed for the 2025 State of the Ecosystem reports: 
	 
1)	Seasonal maps of bottom-water pH on the U.S. Northeast Shelf (2007-2024): access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/pH/bottom_pH/). Includes all available data from 2007-2024 and includes both glider-based measurements and vessel-based discrete samples. See Figure 1 in the Ocean Acidification and Other Stressors catalog page.
2)	Seasonal maps of bottom-water aragonite saturation state (omega) on the U.S. Northeast Shelf (2007-2024): access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/omega/bottom_omega/). Includes all available data from 2007-2024 and includes both glider-based measurements and vessel-based discrete samples. See Figure 2 in the Ocean Acidification and Other Stressors catalog page.
3)	Seasonal maps of surface-water pH on the U.S. Northeast Shelf (2004-2024): access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/pH/surface_pH/). Includes all available data from 2004-2024 and includes both glider-based measurements and vessel-based discrete samples. See Figure 3 in the Ocean Acidification and Other Stressors catalog page.
4)	Seasonal maps of surface-water aragonite saturation state (omega) on the U.S. Northeast Shelf (2004-2024): access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/omega/surface_omega/). Includes all available data from 2004-2024 and includes both glider-based measurements and vessel-based discrete samples. See Figure 4 in the Ocean Acidification and Other Stressors catalog page.
5)	Animated maps of seasonal bottom pH on the U.S. Northeast Shelf (2007-2024): access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/pH/bottom_pH/). Includes all available data from 2007-2024 and includes both glider-based measurements and vessel-based discrete samples.
6)	Animated map of seasonal bottom aragonite saturation state (omega) on the U.S. Northeast Shelf (2007-2024): access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/omega/bottom_omega/). Includes all available data from 2007-2024 and includes both glider-based measurements and vessel-based discrete samples.
7)	Individual maps (by year, 2007-2024) used to make the animated maps for seasonal bottom pH on the U.S. Northeast Shelf: access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/pH/bottom_pH/). Includes all available data from 2007-2024 and includes both glider-based measurements and vessel-based discrete samples.
8)	Individual maps (by year, 2007-2024) used to make the animated maps for seasonal bottom aragonite saturation state (omega) on the U.S. Northeast Shelf: access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/omega/bottom_omega/). Includes all available data from 2007-2024 and includes both glider-based measurements and vessel-based discrete samples.
9)	Animated maps of seasonal surface pH on the U.S. Northeast Shelf (2004-2024): access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/pH/surface_pH/). Includes all available data from 2004-2024 and includes both glider-based measurements and vessel-based discrete samples.
10)	Animated map of seasonal surface aragonite saturation state (omega) on the U.S. Northeast Shelf (2004-2024): access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/omega/surface_omega/). Includes all available data from 2004-2024 and includes both glider-based measurements and vessel-based discrete samples.
11)	Individual maps (by year, 2004-2024) used to make the animated maps for seasonal surface pH on the U.S. Northeast Shelf: access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/pH/surface_pH/). Includes all available data from 2004-2024 and includes both glider-based measurements and vessel-based discrete samples.
12)	Individual maps (by year, 2004-2024) used to make the animated maps for seasonal surface aragonite saturation state (omega) on the U.S. Northeast Shelf: access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/omega/surface_omega/). Includes all available data from 2004-2024 and includes both glider-based measurements and vessel-based discrete samples.
13)	Seasonal maps of locations where species sensitivity levels for aragonite saturation state (omega) were reached in bottom water within the species habitat depth range (2007-2024): access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/bottom_omega_species_sensitivities/). 
a.	Includes all available data from 2007-2024 and includes both glider-based measurements and vessel-based discrete samples.
b.	Sensitivity levels of ΩArag were defined for each species as values of ΩArag where negative responses by an organism were observed during an experimental laboratory study. Typically, these laboratory experiments measure organism responses under ocean acidification conditions (lower pH, lower ΩArag) against a control under ambient conditions (higher pH, higher ΩArag). Most laboratory experiments have used a range of ΩArag between 0.5 to 2.0, which does not encompass the full range of ΩArag observed in situ. The metrics measured (e.g., survival, growth, calcification) can be different between experiments, but negative responses could include decreased survival, reduced growth, reduced calcification rate, reduced hatching success, and malformation. Because laboratory perturbation experiments testing the responses of organisms to ocean acidification conditions are a relatively new approach and logistically quite challenging, there are currently few published studies for individual species. Recent studies have also started incorporating additional stressors, which makes defining an OA-focused sensitivity level difficult. Therefore, with additional future studies, the ΩArag sensitivity levels defined here for these species are subject to change.  
c.	For the Mid-Atlantic region, designated target species included Atlantic sea scallop (Placopecten magellanicus) and Longfin squid (Doryteuthis pealeii). The sensitivity value used for Atlantic sea scallop was ΩArag ≤ 1.1 at 9 °C, based on reduced adult calcification rate observed at this level in Cameron et al. (2022). The sensitivity value used for longfin squid was ΩArag ≤ 0.96, based on embryo and paralarvae malformation, increased time to hatching and decreased hatching success, and changes to mantle length and statolith morphology observed at this level in Zafroff et al. (2019) and Zafroff & Mooney (2020). Habitat depth ranges used for plotting the observed ΩArag values ≤ sensitivity ΩArag values for Atlantic sea scallop and longfin squid were limited to 25-200 meters (NEFSC 2014) and 0-400 meters (Jacobson et al. 2005), respectively. Bottom water data collected during 2024 were incorporated to update this product for the Mid-Atlantic species, Atlantic sea scallop and longfin squid (available [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/bottom_omega_species_sensitivities/)). See Figures 5-6 in the Ocean Acidification and Other Stressors catalog page.
d.	For the New England region, designated target species included Atlantic cod (Gadus morhua) and American lobster (Homarus americanus). The sensitivity value used for Atlantic cod was ΩArag ≤ 1.31 at 10 °C, based on decreased larval survival observed at this level in Stiasny et al. (2016). The sensitivity value used for American lobster was ΩArag ≤ 1.09, based on decreased stage V and VI juvenile survival observed at this level in Noisette et al. (2021). Habitat depth ranges used for plotting the observed ΩArag values ≤ sensitivity ΩArag values for Atlantic cod and American lobster were limited to 10-200 meters (Gregory et al. 2004; DeCelles et al. 2017) and 10-700 meters (Mercaldo-Allen et al. 1994), respectively. Maps for Atlantic cod and American lobster do not include any 2024 data because data from this year for the Gulf of Maine are not available. However, the maps for the individual years between 2012-2023 and the combined map for this same time period are available for these species (available [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/bottom_omega_species_sensitivities/)). See Figures 7-8 in the Ocean Acidification and Other Stressors catalog page.
14)	Maps of bottom temperature anomalies, bottom aragonite saturation state (omega) and satellite-derived surface chlorophyll anomalies for summers 2022-2024: access [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/plots/summer2022-2024/). Anomalies were calculated as the difference from the summer mean 2012-2024. See Figure 9 in the Ocean Acidification and Other Stressors catalog page.

Data processing code can be found on Github [here](https://github.com/lgarzio/cinar-soe), and all data files used in these analyses and plots can be found [here](https://marine.rutgers.edu/~lgarzio/cinar_soe/2025_submission/).

**catalog link** <https://noaa-edab.github.io/catalog/ocean_acidification.html>
