# Fish Productivity Indicators {#productivity_anomaly}
 
**Description**: Fish productivity estimated from surveys and assessments

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2017-2018, 2020, 2022-2024), State of the Ecosystem - Mid-Atlantic (2017-2020, 2022-2024)

**Indicator category**: Database pull with analysis; Published methods

**Contributor(s)**: Sarah Gaichas, Kimberly Bastille, Andy Beet, Charles Perretti
  
**Data steward**: Sarah Gaichas, <sarah.gaichas@noaa.gov>
  
**Point of contact**: Sarah Gaichas, <sarah.gaichas@noaa.gov>
  
**Public availability statement**: Survey source data are available upon request. Stock assessment outputs are available at https://apps-st.fisheries.noaa.gov/stocksmart?app=homepage. 


## Methods


### Data sources
Two sources are used in separate productivity indicators, one based on survey data and one based on stock assessment outputs.

Survey data from the Northeast Fisheries Science Center (NEFSC) trawl database. These data in their derived form are available through the R package [survdat](#survdat), which works within the NEFSC firewall.

Stock assessment outputs are retrieved from the StockSMART website using the R package [stocksmart](https://noaa-edab.github.io/stocksmart/), [@beet_stocksmart_2024]. 


### Data extraction 
Survey data were extracted from [survdat](#survdat). 

Code for retrieving Northeast US stock assessment outputs, along with visualizations of the input information, is available at  https://noaa-edab.github.io/stockstatusindicator/MultisppRec2024.html#get-stocksmart-info

### Data analysis

#### Survey
We defined size thresholds separating small and large fish for each species based on the 20th percentile of the length distribution across all years. This threshold was then used to calculate a small and large fish index (numbers below and above the threshold, respectively) each year. Although the length percentile corresponding to age-1 fish will vary with species, we use the 20th percentile as an approximation. Biomass was calculated using length–weight relationships directly from the survey data. Following @wigley_length-weight_2003, the length-weight relationship was modeled as 
$$\ln W = \ln a + b \ln L$$
where $W$ is weight (kg), $L$ is length (cm), and $a$ and $b$ are parameters fit via linear regression. The ratio of small fish numbers of the following year to larger fish biomass in the current year was used as the index of recruitment success. The fall and spring recruitment success anomalies were averaged to provide an annual index of recruitment success.

Further details of methods described in @perretti_regime_2017.

#### Stock assessments
Stock assessment recruitment estimates for each species were compared with the spawning stock biomass (SSB) estimates from the same assessment. Assessments from 2019 to present were considered. We pulled all Northeast stocks available in stockSMART that had both recruitment and biomass estimates available, and used the most recent assessment year available. Units used in assessments were converted to recruitment in numbers at age 1 for analysis. Recruitment years were aligned with SSB for the year producing the recruitment, depending on the age at recruitment. Units of biomass (all listed as mature/spawning stock or retro adjusted spawning stock) are converted to kg for similarity with survey anomaly code.

Once standardized and aligned, the same calculations described in @perretti_regime_2017 for survey data were applied to the stock assessment outputs. 

Detailed code on all methods is provided at https://noaa-edab.github.io/stockstatusindicator/MultisppRec2024.html 

### Data processing

Productivity data were formatted for inclusion in the `ecodata` R package using the R code found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_productivity_anomaly.R).

**catalog link**
<https://noaa-edab.github.io/catalog/productivity_anomaly.html>