# Fish Productivity Indicator
 
**Description**: Groundfish productivity estimated as the ratio of small fish to large fish

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2017, 2018, 2020), State of the Ecosystem - Mid-Atlantic (2017, 2018, 2019, 2020)

**Indicator category**: Database pull with analysis; Published methods

**Contributor(s)**: Charles Perretti
  
**Data steward**: Charles Perretti, <charles.perretti@noaa.gov>
  
**Point of contact**: Charles Perretti, <charles.perretti@noaa.gov>
  
**Public availability statement**: Source data are available upon request.


## Methods


### Data sources
Survey data from the Northeast Fisheries Science Center (NEFSC) trawl database. These data in their derived form are available through [Survdat](#survdat).


### Data extraction 
Data were extracted from [Survdat](#survdat).


### Data analysis
We defined size thresholds separating small and large fish for each species based on the 20th percentile of the length distribution across all years. This threshold was then used to calculate a small and large fish index (numbers below and above the threshold, respectively) each year. Although the length percentile corresponding to age-1 fish will vary with species, we use the 20th percentile as an approximation. Biomass was calculated using length–weight relationships directly from the survey data. Following @wigley_length-weight_2003, the length-weight relationship was modeled as 
$$\ln W = \ln a + b \ln L$$
where $W$ is weight (kg), $L$ is length (cm), and $a$ and $b$ are parameters fit via linear regression. The ratio of small fish numbers of the following year to larger fish biomass in the current year was used as the index of recruitment success. The fall and spring recruitment success anomalies were averaged to provide an annual index of recruitment success.

Further details of methods described in @perretti_regime_2017.

### Data processing

Productivity data were formatted for inclusion in the `ecodata` R package using the R code found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_productivity_anomaly.R).

### Plotting

```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/macrofauna.Rmd-MAB-recruitment.R"), echo = F, eval = T, message=F, warning=F, fig.cap = "Groundfish productivity across all stocks in the Mid-Atlantic Bight."}

```
