# Quota and Catch - New England 

**Description**: The catch limit (either ABC or ACL) and total catch for all NEFMC species and sector (commercial or recreational), if appropriate.

**Found in**:  State of the Ecosystem - New England (2023) 

**Indicator category**: Synthesis of published information, Database pull

**Contributor(s)**: Kimberly Bastille
  
**Data steward**: Kimberly Bastille <kimberly.bastille@noaa.gov>
  
**Point of contact**: Kimberly Bastille <kimberly.bastille@noaa.gov>
  
**Public availability statement**: Source data are publicly available

## Methods

### Data sources

Data found in NFMS [Species Information System (SIS)](https://apps-st.fisheries.noaa.gov/sis/#no-back-button). 

SIS Annual Catch Limit reports were used to collate data for each Fisheries Management Plan (FMP). The Allowable Biological Catch and Grand Total Catch (Commercial + Recreational) were recorded. 

### Data analysis

Each stock has a threshold and catch value assigned to it from the sources above. The table below outlines the data pull for each FMP. 

|  FMP              | Quota Type  |  Fishing Year    |  
|-------------------|-------------|------------------|
| Atlantic Herring  |  ACL       | January 1 through December 31
| Atlantic Sea Scallop | ACL | Apr 1 through Mar 31
| Red Crab | ACL |  Apr 1 thorugh Mar 31
| Skates | ACL  | May 1 through April 30
| Groundfish | ACL | May 1 through April 30
| Monkfish  | ACL  | May 1 through April 30
| Golden Tilefish | ACL | November 1 through October 31



### Data processing 

Data were formatted for inclusion in the `ecodata` R package using the R code found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_abc.acl.R).

**catalog link**
No associated catalog page