# Recreational Shark Fishing Indicators {#rec_hms}

**Description**: Recreational Shark Landings

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2021+), State of the Ecosystem - Mid-Atlantic (2021+)

**Indicator category**: Database pull with analysis
  
**Contributor(s)**: Kimberly Bastille
  
**Data steward**: Kimberly Bastille, <kimberly.bastille@noaa.gov>
 
**Point of contact**: Kimberly Bastille, <kimberly.bastille@noaa.gov>

**Public availability statement**: Data sets are publicly available (see Data Sources below).


## Methods

### Data sources
All recreational shark fishing indicator data were downloaded from the Marine Recreational Information Program [MRIP Recreational Fisheries Statistics Queries](https://www.st.nmfs.noaa.gov/recreational-fisheries/data-and-documentation/queries/index) portal. 

From the main [Recreational fisheries statistics queries](https://www.fisheries.noaa.gov/data-tools/recreational-fisheries-statistics-queries) page, the [download query](https://www.st.nmfs.noaa.gov/SASStoredProcess/do?) link is available. From here the following selections made include:

| Prompt            | Selected                            |
|-------------------|-------------------------------------|
| Minimum Year      | 1981                                |
| Maximum Year      | *Max year available                 |
| Data Type         | Estimate: Catch                     |
| Wave Options      | All Waves                           |   
| Geographical Area | Not Specified                       |
| Species           | *26 Species outlined in table below |
| Output            | Download CSV as ZIP File            |

The ZIP file was used in the following analysis. 


### Data analysis

Data regions "4 = New England"  and "5 = Mid-Atlantic" were selected for as to remove data from regions not relevant to the State of the Ecosystem reports. The data were then grouped into categories using the table below. This species list was the list used in the above "species" section in the MRIP query.  Data were grouped by year, category and region, and the sum of all the landings for each was used as the indicator for recreational shark harvest. 

| Category       | Common Name          | Species Name                 |
|----------------|----------------------|------------------------------|
| Small Coastal  | Atlantic Sharpnose   | *Rhizoprionodon terraenovae* |
| Small Coastal  | Blacknose            | *Carcharhinus acronotus*     |
| Small Coastal  | Bonnethead           | *Sphyrna tiburo*             |
| Small Coastal  | Finetooth            | *Carcharhinus isodon*        |
| Large Coastal  | Blacktip             | *Carcharhinus limbatus*      |  
| Large Coastal  | Bull                 | *Carcharhinus leucas*        |
| Large Coastal  | Great Hammerhead     | *Sphyrna mokarran*           |
| Large Coastal  | Lemon                | *Negaprion brevirostris*     |
| Large Coastal  | Nurse                | *Ginglymostoma cirratum*     |
| Large Coastal  | Sandbar              | *Carcharhinus plumbeus*      |
| Large Coastal  | Scalloped Hammerhead | *Sphyrna lewini*             |
| Large Coastal  | Silky                | *Carcharhinus falciformis*   |
| Large Coastal  | Smooth Hammerhead    | *Sphyrna zygaena*            | 
| Large Coastal  | Spinner              | *Carcharhinus brevipinna*    |
| Large Coastal  | Tiger                | *Galeocerdo cuvier*          |
| Prohibited     | Atlantic Angel       | *Squatina dumeril*           |
| Prohibited     | Basking              | *Cetorhinus maximus*         |
| Prohibited     | Bigeye Thresher      | *Alopias superciliosus*      |
| Prohibited     | White                | *Carcharodon carcharias*     |
| Pelagic        | Blue                 | *Prionace glauca*            |
| Pelagic        | Dusky                | *Carcharhinus obscurus*      |
| Pelagic        | Oceanic Whitetip     | *Carcharhinus longimanus*    |
| Pelagic        | Porbeagle            | *Lamna nasus*                |
| Pelagic        | Shortfin Mako        | *Isurus oxyrinchus*          |
| Pelagic        | Thresher             | *Alopias vulpinus*           |

### Data processing

Recreational shark fishing indicators were formatted for inclusion in the `ecodata` R package using this [code](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_rec_hms.R).

**catalog link**
<https://noaa-edab.github.io/catalog/rec_hms.html>