# Submerged Aquatic Vegetation {#SAV}

**Description**: Chesapeake Bay Submerged Aquatic Vegetation Trends

**Found in**:  State of the Ecosystem - Mid-Atlantic (2022+) 

**Indicator category**: Database pull with analysis

**Contributor(s)**: David Wilcox, Brooke Landry, Christopher Patrick
  
**Data steward**: David Wilcox <dwilcox@vims.edu>
  
**Point of contact**: David Wilcox <dwilcox@vims.edu>
  
**Public availability statement**: Source data are NOT publicly available. Please email David Wilcox at dwilcox@vims.edu for further information about the submerged aquatic vegetation indicator.

## Methods

### Data Sources
Data for this indicator comes from the aerial survey of submerged aquatic vegetation coverage in the Chesapeake Bay: https://www.chesapeakeprogress.com/abundant-life/sav.

### Data Extraction
The data is available in excel spreadsheet form using the Downloads `Data (.xlsx)` link. The data used is in the “Salinity zone totals” tab and the hectares column can be extracted for each salinity zone.

### Data Analysis 
The [analysis and methods](https://d18lev1ok5leia.cloudfront.net/chesapeakeprogress/chart-assets/submerged-aquatic-vegetation-sav-abundance-1984-2019/Analysis-and-Methods_2020-Submerged-Aquatic-Vegetation_Prelim_070621_final.pdf) are described at the Chesapeake progress page.  

### Data Processing 

Data were formatted for inclusion in the `ecodata` R package using the R code found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_sav.R).