# Warm Core Rings

**Description**: Warm Core Rings

**Found in**: State of the Ecosystem - Mid-Atlantic (2020), State of the Ecosystem - New England (2020)

**Indicator category**: Published Results

**Contributor(s)**: Avijit Gangopadhyay  <avijit.gangopadhyay@umassd.edu>
  
**Data steward**: Avijit Gangopadhyay 
  
**Point of contact**: Avijit Gangopadhyay
  
**Public availability statement**: Data is available upon request. 

## Methods

The plot showing the number of warm core ring formations and regime shift replicates figure 3 in @gangopadhyay2019.  Detailed methods on the warm core ring time series and regime shift analysis are described in the manuscript.

### Data sources


[Gulf Stream charts from Jennifer Clark](https://jcgulfstream.com/charts/) are the primary data source for the warm core ring analysis in @gangopadhyay2019.  The Gulf Stream charts use infra-red (IR) imagery, satellite altimetry data, and surface in-situ temperature data in 3-day composite images are regularly produced by NOAA and/or the Johns Hopkins University Applied Physics Lab (fermi) group (see http://fermi.jhuapl.edu for more details).


### Data extraction 
The data from @gangopadhyay2019 as well as 2018 and 2019 points were provided by Avijit Gangopandhyay, *School for Marine Science and Technology, University of Massachusetts Dartmouth, MA*. 

### Data analysis
A sequential regime shift detection algorithm was used to identify the regimes evident in the warm core ring formation time-series.  See @gangopadhyay2019 for details.

### Data processing
Warm core ring data were formatted for inclusion in the `ecodata` R package using this [R code](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_warm_core_rings.R). 

### Plotting

The plot below was built using the code found
[here](https://github.com/NOAA-EDAB/ecodata/blob/master/chunk-scripts/LTL.Rmd-warm-core-rings.R). 


```{r , code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/LTL.Rmd-warm-core-rings.R"), eval = T, fig.cap= " Interannual Variability of the WCR formation between 1980 and 2019. The regime shift (denoted by the split in the red solid line) is significant at the turn of the century.  Figure reproduced with permission from Gangopadhyay, et al. (2019).  2018 and 2019 data points based on personal communication with A. Gangopadhyay (2020)."}

```
