# Warm Core Rings {#wcr}

**Description**: Warm Core Rings

**Found in**: State of the Ecosystem - Mid-Atlantic (2020+), State of the Ecosystem - New England (2020+)

**Indicator category**: Published Results

**Contributor(s)**: Avijit Gangopadhyay  <avijit.gangopadhyay@umassd.edu>
  
**Data steward**: Avijit Gangopadhyay 
  
**Point of contact**: Avijit Gangopadhyay
  
**Public availability statement**: Data is available upon request. 

## Methods

Detailed methods on the warm core ring time series, regime shift analysis and production of the plots shown in the State of the Ecosystem reports and Northeast US Ecosystem Indicator Catalog are described in in @gangopadhyay2019.

### Data sources


[Gulf Stream charts from Jennifer Clark](https://jcgulfstream.com/charts/) are the primary data source for the warm core ring analysis in @gangopadhyay2019.  The Gulf Stream charts use infra-red (IR) imagery, satellite altimetry data, and surface in-situ temperature data in 3-day composite images are regularly produced by NOAA and/or the Johns Hopkins University Applied Physics Lab (fermi) group (see http://fermi.jhuapl.edu for more details).


### Data extraction 
The data from @gangopadhyay2019 were provided by Avijit Gangopandhyay, *School for Marine Science and Technology, University of Massachusetts Dartmouth, MA*. 

### Data analysis
A sequential regime shift detection algorithm was used to identify the regimes evident in the warm core ring formation time-series.  See @gangopadhyay2019 for details.

### Data processing
Warm core ring data were formatted for inclusion in the `ecodata` R package using this [R code](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_warm_core_rings.R).

**catalog link**
<https://noaa-edab.github.io/catalog/wcr.html>