# Wind Energy Development Timeline {#wind_dev_speed}

**Description**: Wind Energy Lease Area Development 

**Found in**: State of the Ecosystem - New England (2021+), State of the Ecosystem - Mid-Atlantic (2021+), State of the Ecosystem - Indicator Catalog (2024+)

**Indicator category**: Published methods; Synthesis of published information; Database pull with analysis

**Contributor(s)**: Nicole Mucci, Joshua Hatch, Angela Silva, Data steward: Nicole Mucci, Angela Silva
  
**Data steward**: Nicole Mucci <nicole.mucci@noaa.gov>, Angela Silva <angela.silva@noaa.gov>
  
**Point of contact**: Nicole Mucci <nicole.mucci@noaa.gov>, Angela Silva <angela.silva@noaa.gov>
  
**Public availability statement**: Source data are publicly available. Please email <nicole.mucci@noaa.gov> for further information and queries of Wind Energy Development Timeline indicator source data.

## Methods

### Data sources

BOEM lease areas: https://www.boem.gov/renewable-energy/mapping-and-data/renewable-energy-gis-data
BOEM lease construction status: https://www.boem.gov/renewable-energy/offshore-renewable-activities
NOAA ENC - Turbine Foundation Locations: https://www.nauticalcharts.noaa.gov/charts/noaa-enc.html

### Data analysis

Lease area acreage was obtained from the ‘Acres’ column of the attribute table in the Bureau of Ocean Energy Management’s (BOEM) ArcGIS Online (AGOL) hosted feature service, “Wind Lease Boundaries BOEM - Offshore Wind Lease Outlines”. To the extent possible, acreage values were verified against official lease documents. In the event of a discrepancy or missing data, the acreage reported in the official lease document was used (see Table 1). Note that a single lease area may comprise multiple projects (for example, the Empire Wind lease area comprises the Empire Wind 1 and Empire Wind 2 projects).

Table 1: List of discrepancies or missing acreage data between the BOEM hosted feature service and official lease documents.

| Lease Number | Hosted Feature Service Acreage | Lease Document Acreage |
|--------------|--------------------------------|------------------------|
| OCS-A 0486   | 83,789                         | 83,798                 |
| OCS-A 0520   | 128,881                        | 128,811                |
| OCS-A 0534   | NA (missing)                   | 52,663                 |
| OCS-A 0561   | NA (missing)                   | 48,927                 |
| OCS-A 0570   | 43,439                         | 43,412                 |

Turbine Foundations
The number of turbine foundations in each lease area, either proposed or installed, was tallied using the NOAA Electronic Navigational Charts (ENCs).

### Data processing 

Data were formatted for inclusion in the `ecodata` R package using the R code found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_wind_dev_speed.R).

**catalog link**
<https://noaa-edab.github.io/catalog/wind_dev_speed.html>