# Fisheries Revenue in Wind Development Areas

**Description**: Top 5 Species Revenue from Wind Development Areas

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2021), State of the Ecosystem - Mid-Atlantic (2021)

**Indicator category**: Published methods, Extension of published methods.

**Contributor(s)**: Geret DePiper, Dennis Corvi, Benjamin Galluardi, Douglas Christel, Eric Thunberg
  
**Data steward**: Geret DePiper
  
**Point of contact**: Geret DePiper <geret.depiper@noaa.gov>
  
**Public availability statement**: Source data are NOT publicly available. Please email geret.depiper@noaa.gov for further information and queries of indicator source data.

## Methods
### Data Sources

This indicator is derived from the data underpinning the "Sociceoeconomic Impacts of Atlantic Offshore Wind Development" web site, which can be accessed at https://www.fisheries.noaa.gov/resource/data/socioeconomic-impacts-atlantic-offshore-wind-development.

The underlying raster data is defined in Benjamin S, Lee MY, DePiper G. 2018. Visualizing fishing data as rasters. NEFSC Ref Doc 18-12; 24 p.

This raster data was then linked to the Greater Atlantic Regional Office's Data Matching Imputation System (https://www.fisheries.noaa.gov/inport/item/17328) to derive revenue estimates from the Wind Energy Areas, defined as of December 11, 2020. Of note is that the version of DMIS utilized for this reporting includes the SFCLAM data missing from the traditional DMIS dataset. All revenue estimates are deflated to 2019 dollars using the St. Louis Federal Reserve's Quarterly Implicit GDP Deflator, which can be accessed at https://fred.stlouisfed.org/data/GDPDEF.txt

### Data Analysis
Code used to analyze this data can be [found here](https://github.com/NOAA-EDAB/tech-doc/blob/master/R/stored_scripts/WindRevenue_Code_for_Dissemination.R)

### Data Processing 

Data were formatted for inclusion in the `ecodata` R package using the R code found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_wind_dev_speed.R).

### Plotting

The plot below was built using the code found
[here](https://github.com/NOAA-EDAB/ecodata/blob/master/chunk-scripts/human_dimensions_MAB.Rmd-wind-revenue.R). 

```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/human_dimensions_MAB.Rmd-wind-revenue.R"), eval = T, echo = F, fig.cap = "Top five species revenue found in wind development areas."}

```

