# WEA Fishing Port Landings 

**Description**: Port Landings from within Wind Lease Areas and Community Social Vulnerability Indicators

**Found in**: State of the Ecosystem - Gulf of Maine & Georges Bank (2022+), State of the Ecosystem - Mid-Atlantic (2022+)

**Indicator category**: Port Landings from within Wind Lease Areas and Community Social Vulnerability Indicators

**Contributor(s)**: Angela Silva, Doug Christel
  
**Data steward**: Angela Silva
  
**Point of contact**: Angela Silva <angela.silva@noaa.gov>
  
**Public availability statement**: Source data are NOT publicly available. Please email angela.silva@noaa.gov for further information and queries of Speed and Extent of Offshore Wind Development indicator source data.

## Methods
### Data Sources
Social Indicators Data: 
*https://www.fisheries.noaa.gov/national/socioeconomics/social-indicators-coastal-communities
*https://www.st.nmfs.noaa.gov/data-and-tools/social-indicators/

Wind Data: 
*https://www.greateratlantic.fisheries.noaa.gov/ro/fso/reports/WIND/ALL_WEA_BY_AREA_DATA.html
*https://www.fisheries.noaa.gov/resource/data/socioeconomic-impacts-atlantic-offshore-wind-development


### Data Analysis

Cumulative port landings(pounds) and revenue(dollars) from Wind Energy Areas (WEA) were pulled for communities along the Northeast US Shelf from 2010 to 2019. Percent of wind lease area landings were calculated compared to total landings for those communities. Environmental Justice and Gentrification Vulnerability were then matched to these communities. 


### Data Processing 

Data were formatted for inclusion in the `ecodata` R package using the R code found [here](https://github.com/NOAA-EDAB/ecodata/blob/master/data-raw/get_wind_port.R).

### Plotting

The plot below was built using the code found
[here](https://github.com/NOAA-EDAB/ecodata/blob/master/chunk-scripts/human_dimensions_MAB.Rmd-wind-port-rev.R).


```{r, code = readLines("https://raw.githubusercontent.com/NOAA-EDAB/ecodata/master/chunk-scripts/human_dimensions_MAB.Rmd-wea-port-rev.R"), eval = T, echo = F, fig.cap = ""}

```








